import type { ReligionContent } from './types';

export const christianity: ReligionContent = {
  name: 'Christianity',
  family: 'Abrahamic tradition',
  overview: `Christianity is the world's largest religion, with an estimated 2.3 to 2.4 billion adherents across virtually every country on Earth [1][4]. The tradition traces its origins to the 1st century CE in the eastern Mediterranean region of Roman Judea, centered on the life, teachings, death, and reported resurrection of Jesus of Nazareth [2][3]. Early followers, initially a movement within Second Temple Judaism, gradually developed distinct communal identities, worship practices, and theological frameworks that distinguished them from other Jewish groups of the period [2][3].

Over the following centuries, Christianity spread throughout the Roman Empire and beyond, becoming the official religion of Rome under Emperor Theodosius I in 380 CE [2][3]. The tradition subsequently expanded into Europe, Africa, Asia, and eventually the Americas, shaped by missionary activity, colonial history, and local adaptation [2][3]. Today, Christianity encompasses an extraordinarily diverse family of churches, denominations, and movements, ranging from Roman Catholicism and Eastern Orthodoxy to thousands of Protestant and independent church bodies [1][2].

What unites most Christian communities is a shared reference to Jesus Christ as central to faith and practice, the use of the Bible as scripture (though canons vary), and rituals such as baptism and communal worship [2][3]. Beyond these commonalities, however, Christians hold widely varying views on theology, ethics, church governance, and the interpretation of sacred texts. The tradition's global footprint means it has been shaped by, and has shaped, cultures on every inhabited continent [1][2]. For dedicated coverage of Catholic and Eastern Orthodox traditions, see the Catholicism and Orthodox Christianity pages on this site.`,
  beliefs: `At the broadest level, most Christian traditions affirm belief in one God, though the understanding of God's nature varies across denominations [2][3]. The doctrine of the Trinity, that God exists as Father, Son, and Holy Spirit, three persons in one divine being, is affirmed by Catholic, Orthodox, and most Protestant churches, as articulated in early ecumenical creeds such as the Nicene Creed (325/381 CE) [2][3]. Some Christian groups, including certain Unitarian traditions and others, hold different views on this doctrine [2][3].

Central to Christian theology is the person of Jesus Christ. Most mainstream traditions teach that Jesus is both fully divine and fully human, a formulation established at the Council of Chalcedon in 451 CE [2][3]. Christians generally believe that Jesus's death served as an atoning sacrifice for human sin, and that his resurrection from the dead offers the promise of eternal life to believers [2][3]. The specific mechanics of salvation, whether by faith alone, by faith and works, through sacraments, or by divine grace, are among the most debated questions across Christian denominations [2][3].

The concept of sin is foundational in Christian anthropology. Many traditions teach that humanity exists in a state of separation from God due to original sin, traced to the narrative of Adam and Eve in the book of Genesis [2][3]. Redemption through Christ is understood as the remedy for this condition, though interpretations of what redemption requires of the individual vary significantly [2][3].

Christian eschatology, beliefs about the end times and final destiny, includes themes of Christ's return, a final judgment, and the establishment of God's kingdom [2][3]. Views on the timeline, literalness, and nature of these events differ widely, from premillennialism to amillennialism to postmillennialism, and from literal to symbolic readings of prophetic texts [2][3].`,
  practices: `Christian worship practices vary enormously across traditions, but most communities gather regularly, typically on Sundays, for communal prayer, scripture reading, preaching, and some form of the Eucharist or Communion [2][3]. In Catholic and Orthodox traditions, the liturgy follows structured rites with roots in early church practice, while many Protestant churches adopt less formal worship styles [2][3].

Baptism is nearly universal as an initiation rite, though its form (immersion, pouring, or sprinkling) and timing (infant or believer's baptism) differ by denomination [2][3]. The Eucharist or Lord's Supper is the other most widely practiced sacrament, with Catholic and Orthodox churches teaching the real presence of Christ in the bread and wine, while many Protestant traditions view it as symbolic or memorial [2][3].

Prayer is central to Christian devotional life. Forms range from structured liturgical prayers and the recitation of the rosary in Catholic practice to extemporaneous prayer in evangelical and Pentecostal settings [2][3]. Monastic traditions in both Catholic and Orthodox Christianity maintain daily prayer offices (the Liturgy of the Hours) that structure the entire day around worship [2][3].

Major Christian holidays include Christmas (celebrating the birth of Jesus, observed December 25 in Western churches and January 7 in many Eastern churches), Easter (celebrating the resurrection, with dates varying by calendar), Lent (a 40-day period of fasting and penitence before Easter), Pentecost, and Advent [2][3]. The liturgical calendar varies by tradition, with Catholic and Orthodox churches observing a more extensive cycle of saints' days and feast days [2][3].

Rites of passage include baptism, confirmation or chrismation, marriage, ordination, and funeral rites. Catholic tradition recognizes seven sacraments, while most Protestant churches recognize two (baptism and communion) [2][3]. Pilgrimage, while not obligatory, remains important in many traditions, with destinations including Jerusalem, Rome, Santiago de Compostela, Lourdes, and Fatima [2][3].`,
  texts: `The Bible is the central scripture of Christianity, though its exact contents vary by tradition [2][3]. The Protestant Bible contains 66 books (39 Old Testament, 27 New Testament), while Catholic Bibles include an additional seven deuterocanonical books, and Orthodox canons may include further texts [2][3]. The Old Testament (or Hebrew Bible) contains the Torah, historical books, wisdom literature, and prophetic writings. The New Testament includes four Gospels (Matthew, Mark, Luke, and John), the Acts of the Apostles, epistles attributed to Paul and other early leaders, and the book of Revelation [2][3].

The Gospels narrate the life, ministry, death, and resurrection of Jesus. Paul's epistles, written in the mid-1st century CE, are among the earliest Christian documents and address theology, ethics, and church organization [2][3]. The New Testament canon was largely settled by the 4th century CE, though debates about certain books continued for some time [2][3].

Christians have produced an enormous body of interpretive and theological literature over two millennia, including the writings of the Church Fathers, medieval scholastic theology, Reformation-era confessions, and modern biblical scholarship [2][3]. Different traditions assign varying levels of authority to these secondary sources alongside scripture [2][3].

"In the beginning was the Word, and the Word was with God, and the Word was God.", John 1:1, King James Version, 1611 (public domain) [6]. This opening verse of John's Gospel is among the most widely quoted passages in Christian scripture, expressing the theological concept of the Logos [2][3].`,
  demographics: `Christianity is the world's largest religion by adherent count, with approximately 2.3 to 2.4 billion followers as of recent estimates [1][4]. This represents roughly 31% of the global population [1]. Christians are found in significant numbers on every inhabited continent, making it the most geographically widespread religion [1][4].

The largest single denomination is the Roman Catholic Church, with approximately 1.3 billion members [1][4]. Eastern Orthodox churches collectively account for roughly 220 million adherents [1]. Protestant and independent churches are extremely diverse, numbering in the tens of thousands of denominations and collectively comprising several hundred million members [1][4].

Historically concentrated in Europe, Christianity's demographic center has shifted significantly over the past century [1]. Sub-Saharan Africa and Latin America now contain the largest Christian populations, and growth rates are highest in parts of Africa, Asia, and the Global South [1][4]. Europe, by contrast, has seen declining church attendance and rising secularization in many countries [1][4].

The United States remains the country with the largest single Christian population (approximately 230 million), followed by Brazil, Mexico, Russia, and the Philippines [1][4]. China's Christian population, while difficult to measure precisely due to the presence of unregistered churches, is estimated in the tens of millions and growing [1][4].`,
  timeline: `The history of Christianity spans two millennia and encompasses enormous geographic, cultural, and theological diversity [2][3]. Key developments include:

c. 4 BCE – c. 30 CE: Life of Jesus of Nazareth in Roman Judea [2][3]. c. 50-60 CE: Paul's missionary journeys and earliest New Testament writings [2][3]. 70 CE: Destruction of the Second Temple in Jerusalem, accelerating the separation of Christianity from Judaism [2][3]. 313 CE: Edict of Milan grants legal toleration to Christians in the Roman Empire [2][3]. 325 CE: Council of Nicaea produces the Nicene Creed, addressing Trinitarian theology [2][3]. 380 CE: Christianity becomes the official religion of the Roman Empire under Theodosius I [2][3]. 451 CE: Council of Chalcedon defines the two-nature Christology accepted by most mainstream churches [2][3]. 1054 CE: The Great Schism formally divides the Latin (Catholic) West and Greek (Orthodox) East [2][3]. 1095-1291: The Crusades reshape Christian-Muslim relations and European engagement with the Middle East [2][3]. 1517: Martin Luther posts the 95 Theses, catalyzing the Protestant Reformation [2][3]. 1534: Henry VIII establishes the Church of England [2][3]. 1545-1563: Council of Trent defines Catholic Counter-Reformation positions [2][3]. 1962-1965: Second Vatican Council modernizes Catholic liturgy and interfaith engagement [2][3]. 20th-21st century: Rapid growth of Christianity in the Global South, rise of Pentecostalism, and ecumenical dialogue movements [1][2][3].`,
  denominations: `Christianity contains an extraordinary diversity of denominations, traditions, and independent church bodies [2][3]. The three broadest historical groupings are:

Roman Catholicism: The largest single Christian body, with approximately 1.3 billion members worldwide, led by the Pope in Rome [1][2]. Catholic theology emphasizes apostolic succession, seven sacraments, the authority of tradition alongside scripture, and the teaching authority (magisterium) of the Church [2][3]. For full coverage, see the dedicated Catholicism page on this site.

Eastern Orthodoxy: A family of autocephalous (self-governing) churches with approximately 220 million members, including the Greek, Russian, Serbian, Romanian, and other national churches [1][2]. Orthodox theology emphasizes theosis (deification), the authority of the ecumenical councils, and a rich liturgical and iconographic tradition [2][3]. For full coverage, see the dedicated Orthodox Christianity page on this site.

Protestantism: A diverse family of traditions originating from the 16th-century Reformation, including Lutheran, Reformed/Calvinist, Anglican, Baptist, Methodist, Pentecostal, and many independent churches [2][3]. Protestant theology generally emphasizes scripture as the primary authority (sola scriptura), justification by faith, and the priesthood of all believers, though specific doctrines vary widely [2][3].

Additional groups include Oriental Orthodox churches (Coptic, Ethiopian, Armenian, Syriac), the Assyrian Church of the East, and various restorationist movements [2][3]. The Church of Jesus Christ of Latter-day Saints and Jehovah's Witnesses are sometimes categorized separately; see their dedicated pages on this site [2].`,
  holidays: `The Christian liturgical calendar varies by tradition but includes several widely observed seasons and feast days [2][3]:

Christmas (December 25 in Western churches; January 7 in many Eastern churches): Celebrates the birth of Jesus. The season of Advent (four weeks before Christmas) is a period of preparation [2][3]. Easter: The most important Christian feast, celebrating the resurrection of Jesus. The date varies annually (March-April in Western churches; sometimes different in Eastern churches due to calendar differences). Holy Week, including Palm Sunday, Maundy Thursday, and Good Friday, precedes Easter [2][3]. Lent: A 40-day period of fasting, prayer, and penitence before Easter, observed in Catholic, Orthodox, Anglican, and many other traditions [2][3]. Pentecost: Celebrated 50 days after Easter, marking the descent of the Holy Spirit on the apostles [2][3]. Epiphany (January 6): Commemorates the visit of the Magi in Western tradition and the baptism of Jesus in Eastern tradition [2][3].

Catholic and Orthodox churches observe extensive calendars of saints' days, Marian feasts, and other commemorations throughout the year [2][3]. Protestant observance of the liturgical calendar varies widely, with some traditions following it closely and others focusing primarily on Christmas and Easter [2][3].`,
  leadership: `Christian leadership structures vary dramatically across traditions [2][3]:

In the Roman Catholic Church, the Pope serves as the supreme head, supported by cardinals, archbishops, bishops, priests, and deacons in a hierarchical episcopal structure [2][3]. The doctrine of papal infallibility (defined in 1870) applies under specific conditions when the Pope speaks ex cathedra on matters of faith and morals [2][3].

Eastern Orthodox churches are governed by a conciliar model, with each autocephalous church led by a patriarch, metropolitan, or archbishop. The Ecumenical Patriarch of Constantinople holds a position of honor (first among equals) but does not exercise authority over other Orthodox churches [2][3].

Protestant governance models include episcopal (bishops, as in Anglican and some Lutheran churches), presbyterian (governance by elders, as in Reformed traditions), and congregational (local church autonomy, as in Baptist and many independent churches) [2][3]. Some traditions have no formal clergy at all [2][3].

Monastic orders play significant roles in Catholic and Orthodox Christianity, with communities of monks and nuns following rules of life such as the Rule of St. Benedict (Catholic) or the traditions of Mount Athos (Orthodox) [2][3].`,
  symbols: `The cross is the most widely recognized symbol of Christianity, representing the crucifixion and resurrection of Jesus [2]. Different traditions use different forms: the Latin cross (most common in Western Christianity), the Eastern Orthodox cross (with additional crossbars), the Celtic cross, and the crucifix (a cross bearing the figure of Christ, common in Catholic and some Lutheran churches) [2][3].

Other significant symbols include the ichthys (fish), an early Christian symbol used as a secret sign of faith during periods of persecution [2]. The chi-rho, combining the first two Greek letters of "Christ," was adopted by Emperor Constantine and appears in early Christian art [2][3]. The dove represents the Holy Spirit, and the lamb symbolizes Jesus as the "Lamb of God" [2][3].

Iconography is particularly important in Eastern Orthodox Christianity, where icons of Christ, the Virgin Mary, and saints serve as windows into the divine and are venerated (though not worshipped) in liturgical practice [2][3]. Catholic churches feature extensive visual art including stained glass, statuary, and paintings [2][3]. Many Protestant traditions, particularly those influenced by Reformed theology, adopt simpler visual aesthetics [2][3].`,
  keyFigures: `Jesus of Nazareth (c. 4 BCE – c. 30 CE) is the central figure of Christianity, regarded by believers as the Son of God, the Messiah, and the savior of humanity [2][3]. The twelve apostles, particularly Peter and Paul, played foundational roles in the early church's expansion and theological development [2][3].

Paul of Tarsus (c. 5 – c. 64 CE) is often considered the most influential early Christian theologian. His letters form a significant portion of the New Testament and address core doctrines including justification by faith, the nature of the church, and Christian ethics [2][3].

The Church Fathers, including Augustine of Hippo, Athanasius, John Chrysostom, and Jerome, shaped Christian theology, biblical interpretation, and institutional development in the first several centuries [2][3]. Thomas Aquinas (1225-1274) produced the Summa Theologica, a foundational work of Catholic scholastic theology [2][3].

The Protestant Reformation produced figures including Martin Luther (1483-1546), John Calvin (1509-1564), and Huldrych Zwingli (1484-1531), whose theological innovations reshaped Western Christianity [2][3]. John Wesley (1703-1791) founded Methodism, and later figures like William Seymour helped launch the Pentecostal movement in the early 20th century [2][3].`,
  ethics: `Christian ethics draw on scripture, tradition, reason, and experience, with different traditions weighting these sources differently [2][3]. The teachings attributed to Jesus in the Gospels, particularly the Sermon on the Mount (Matthew 5-7, KJV, 1611, public domain), emphasize love, mercy, forgiveness, humility, and care for the poor and marginalized [2][3][6].

The Great Commandment, as recorded in the Gospels, summarizes Christian ethical obligation: love of God and love of neighbor [2][3]. The Golden Rule, "Therefore all things whatsoever ye would that men should do to you, do ye even so to them" (Matthew 7:12, KJV, 1611, public domain) [6], is a widely cited ethical principle [2][3].

Catholic moral theology draws on natural law theory, the magisterium, and a detailed sacramental framework [2][3]. Orthodox ethics emphasize theosis and the transformation of the whole person through participation in the divine life [2][3]. Protestant ethical traditions range from Lutheran two-kingdoms theology to Reformed transformationism to evangelical personal morality frameworks [2][3].

Contemporary Christian ethics engage with issues including social justice, economic inequality, environmental stewardship, bioethics, war and peace, gender and sexuality, and interfaith relations [2][3]. Christians hold widely varying positions on these issues, often reflecting denominational, cultural, and political contexts [2][3].`,
  afterlife: `Most Christian traditions teach that human beings have an eternal soul or spirit that continues after physical death [2][3]. The specific understanding of what happens after death varies significantly across denominations [2][3].

Catholic teaching includes the concepts of heaven (eternal communion with God), hell (eternal separation from God), and purgatory (a state of purification for those who die in God's grace but are not yet fully purified) [2][3]. Orthodox theology speaks of the soul's journey after death and the final resurrection but generally avoids the detailed juridical categories of Western theology [2][3].

Most Protestant traditions affirm heaven and hell but reject the concept of purgatory [2][3]. Views on hell range from eternal conscious torment to annihilationism (the belief that the unsaved cease to exist) to universalism (the belief that all will eventually be reconciled to God) [2][3].

Central to Christian eschatology is the belief in the bodily resurrection of the dead and a final judgment [2][3]. The Apostles' Creed affirms "the resurrection of the body and the life everlasting," and the Nicene Creed speaks of looking "for the resurrection of the dead, and the life of the world to come" [2][3]. The book of Revelation provides vivid imagery of end-times events, interpreted literally by some and symbolically by others [2][3].`,
  origins: `Christianity emerged within the diverse religious landscape of 1st-century Roman Judea, a context shaped by Second Temple Judaism, Hellenistic culture, and Roman imperial rule [2][3]. The earliest followers of Jesus were Jewish, and the movement initially existed as a sect within Judaism before gradually developing its own distinct identity [2][3].

The historical Jesus was born in the region of Galilee or Judea (scholars debate the precise location and date, commonly placing his birth around 4 BCE) and conducted a public ministry of teaching, healing, and gathering disciples [2][3]. His execution by crucifixion under the Roman prefect Pontius Pilate (c. 30-33 CE) and the subsequent reports of his resurrection became the foundational events of the Christian faith [2][3].

The apostle Paul's missionary journeys in the 40s-60s CE were instrumental in spreading Christianity beyond its Jewish origins to Gentile (non-Jewish) communities across the eastern Mediterranean [2][3]. The destruction of the Jerusalem Temple in 70 CE further accelerated the divergence between Christianity and rabbinic Judaism [2][3].

By the 2nd and 3rd centuries, Christian communities had established themselves across the Roman Empire, developing institutional structures, liturgical practices, and theological literature [2][3]. The conversion of Emperor Constantine in the early 4th century and the subsequent Christianization of the Roman state transformed the religion from a persecuted minority movement into the dominant faith of the Western world [2][3].`,
  sourceSix: 'King James Version (1611), public domain (reference edition for biblical quotations).',
  sourceSixUrl: 'https://www.kingjamesbibleonline.org/',
};
