import type { ReligionContent } from './types';

export const hinduism: ReligionContent = {
  name: 'Hinduism',
  family: 'Dharmic tradition',
  overview: `Hinduism is the world's third-largest religion and the oldest major living religious tradition, with approximately 1.2 billion adherents, about 15% of the global population [1][4]. Unlike most other major religions, Hinduism has no single founder, no single scripture, and no single set of teachings [2][3]. Instead, it encompasses an extraordinarily diverse family of beliefs, practices, philosophies, and cultural traditions that developed over thousands of years on the Indian subcontinent [2][3].

The term "Hindu" originally referred to people living beyond the Indus River and was used by outsiders; the concept of Hinduism as a unified religion is partly a modern construction, though the traditions it encompasses are ancient [2][3]. Hindus themselves may use terms like Sanatana Dharma ("eternal order" or "eternal duty") to describe their tradition [2][3].

Hindu traditions share certain broadly common elements, including reverence for the Vedas (though the degree of authority assigned to them varies), concepts of dharma (duty/righteousness), karma (action and its consequences), samsara (the cycle of birth, death, and rebirth), and moksha (liberation from this cycle) [2][3]. The tradition encompasses monotheistic, polytheistic, pantheistic, and even atheistic philosophical schools [2][3].

India is home to approximately 94% of the world's Hindu population [1][4]. Significant Hindu communities also exist in Nepal (where Hinduism was historically the state religion), Bangladesh, Indonesia (particularly Bali), Sri Lanka, and diaspora communities worldwide [1][4].`,
  beliefs: `Hindu beliefs are remarkably diverse, spanning multiple philosophical schools (darshanas) and devotional traditions [2][3]. Several concepts appear across many Hindu traditions, though their interpretation varies significantly:

Brahman: Many Hindu philosophies posit an ultimate reality or cosmic principle called Brahman [2][3]. In Advaita Vedanta, Brahman is the sole reality and the individual self (atman) is ultimately identical with it [2][3]. In Vishishtadvaita and Dvaita schools, the relationship between God, the self, and the world is understood differently [2][3]. Dharma: A multivalent concept encompassing cosmic order, moral duty, righteousness, and the proper conduct of life according to one's station and stage of life (varnashrama dharma) [2][3]. Karma: The principle that actions have consequences that shape one's future circumstances, both in this life and in future lives [2][3]. Samsara: The cycle of birth, death, and rebirth through which all living beings pass [2][3]. Moksha: Liberation from the cycle of samsara, understood differently across traditions, as union with Brahman, as eternal devotion to a personal God, or as the realization of the self's true nature [2][3].

Hindu traditions recognize many deities, with Brahma (creator), Vishnu (preserver), and Shiva (transformer/destroyer) often described as a triad [2][3]. Devotional (bhakti) traditions center on particular deities, Vaishnavism on Vishnu and his avatars (especially Krishna and Rama), Shaivism on Shiva, and Shaktism on the Goddess (Devi) in her many forms [2][3]. These are not understood as competing religions but as different paths within the broader Hindu framework [2][3].`,
  practices: `Hindu practice is extraordinarily varied, reflecting the tradition's regional, sectarian, and philosophical diversity [2][3].

Puja (worship) is the most common form of Hindu devotion, performed at home shrines and in temples [2][3]. It typically involves offerings of flowers, food, incense, and light to a deity's image (murti), accompanied by prayers and mantras [2][3]. Temple worship may include elaborate rituals conducted by trained priests (pujaris) [2][3].

Yoga and meditation, while now globally popular as wellness practices, have deep roots in Hindu philosophical and ascetic traditions [2][3]. The Yoga Sutras of Patanjali outline an eight-limbed path of ethical discipline, physical postures, breath control, and meditation [2][3].

Major festivals include Diwali (the festival of lights, celebrating the triumph of light over darkness), Holi (the festival of colors, marking the arrival of spring), Navaratri (nine nights honoring the Goddess), Ganesh Chaturthi, and Maha Shivaratri [2][3]. Festival observances vary significantly by region [2][3].

Pilgrimage (tirtha yatra) is an important practice, with major destinations including Varanasi, Haridwar, Rishikesh, Puri, Tirupati, and the Char Dham circuit [2][3]. The Kumbh Mela, held every 12 years at the confluence of sacred rivers, is one of the largest religious gatherings in the world, attracting tens of millions of participants [1][2][3].

Life-cycle rituals (samskaras) mark major transitions including birth, naming, initiation (upanayana), marriage, and death [2][3]. Cremation is the most common funeral practice, with ashes often immersed in a sacred river [2][3].`,
  texts: `Hinduism possesses one of the most extensive bodies of sacred literature of any world religion [2][3]. These texts are traditionally classified as shruti ("that which is heard", considered divinely revealed) and smriti ("that which is remembered", composed by human authors) [2][3].

The Vedas are the oldest and most authoritative Hindu scriptures, composed in Sanskrit over a period spanning roughly 1500-500 BCE [2][3]. The four Vedas, Rigveda, Samaveda, Yajurveda, and Atharvaveda, contain hymns, ritual instructions, and philosophical speculation [2][3]. The Upanishads, philosophical texts appended to the Vedas, explore the nature of Brahman, atman, and the path to liberation [2][3].

"From the unreal lead me to the real; from darkness lead me to light; from death lead me to immortality.", Brihadaranyaka Upanishad 1.3.28, Max Muller translation (public domain) [6]. This prayer captures a central aspiration of Hindu spiritual life [2][3].

The two great epics, the Mahabharata (which includes the Bhagavad Gita) and the Ramayana, are among the most influential works in Hindu culture [2][3]. The Bhagavad Gita, a dialogue between the warrior Arjuna and the god Krishna, addresses duty, devotion, knowledge, and the nature of reality [2][3]. The Puranas contain mythological narratives, genealogies, and cosmological accounts [2][3].

Additional important texts include the Dharma Shastras (legal and ethical codes), the Yoga Sutras of Patanjali, and the devotional poetry of saints across regional languages [2][3].`,
  demographics: `Hinduism has approximately 1.2 billion adherents worldwide, making it the third-largest religion after Christianity and Islam [1][4]. Hindus constitute approximately 15% of the global population [1].

India is home to approximately 94% of the world's Hindus, with Hindus comprising roughly 80% of India's population [1][4]. Nepal has the second-largest Hindu population, with Hinduism practiced by approximately 81% of Nepalis [1][4]. Bangladesh, Indonesia (particularly Bali), Sri Lanka, and Pakistan also have significant Hindu populations [1][4].

Hindu diaspora communities are found worldwide, with notable populations in the United States (approximately 2.5 million), the United Kingdom, Canada, Australia, South Africa, Trinidad and Tobago, Guyana, Fiji, Mauritius, and the Gulf states [1][4]. These diaspora communities maintain temples, cultural organizations, and educational institutions [1][4].

Hinduism's growth rate roughly tracks global population growth, with its share of the world population expected to remain relatively stable in coming decades [1]. Within India, urbanization, education, and modernization are reshaping religious practice, with some observers noting both secularizing trends and revivalist movements [1][2][3].`,
  timeline: `Hindu traditions have developed over thousands of years, making precise dating challenging for earlier periods [2][3]:

c. 1500-1200 BCE: Composition of the earliest Vedic hymns (Rigveda) [2][3]. c. 1200-900 BCE: Later Vedic period; composition of Samaveda, Yajurveda, Atharvaveda [2][3]. c. 800-200 BCE: Composition of the major Upanishads [2][3]. c. 500 BCE-500 CE: Composition of the great epics (Mahabharata, Ramayana) and early Puranas [2][3]. c. 200 BCE: Patanjali compiles the Yoga Sutras [2][3]. c. 200 BCE-200 CE: Composition of the Bhagavad Gita (within the Mahabharata) [2][3]. c. 300-500 CE: Gupta period; flourishing of Hindu art, temple architecture, and literature [2][3]. c. 500-1000 CE: Development of major bhakti (devotional) movements across South India [2][3]. 788-820 CE: Life of Adi Shankara, who systematized Advaita Vedanta [2][3]. 1017-1137 CE: Life of Ramanuja, who developed Vishishtadvaita Vedanta [2][3]. 1100-1700 CE: Bhakti movement spreads across North India (Kabir, Mirabai, Tulsidas, Chaitanya) [2][3]. 1828: Ram Mohan Roy founds the Brahmo Samaj, a Hindu reform movement [2][3]. 1893: Swami Vivekananda addresses the Parliament of the World's Religions in Chicago [2][3]. 1947: Indian independence; India established as a secular republic with a Hindu majority [2][3]. 20th-21st century: Global spread of Hindu practices including yoga and meditation [1][2][3].`,
  denominations: `Hinduism's internal diversity is organized not into denominations in the Protestant Christian sense but into devotional traditions (sampradayas), philosophical schools (darshanas), and regional practices [2][3].

Vaishnavism: Devotion to Vishnu and his avatars, especially Krishna and Rama. The largest Hindu tradition by adherent count, with major sub-traditions including Sri Vaishnavism, Gaudiya Vaishnavism (ISKCON/Hare Krishna), and Swaminarayan [2][3]. Shaivism: Devotion to Shiva. Includes diverse traditions such as Kashmir Shaivism, Shaiva Siddhanta, Lingayatism, and the Nath tradition [2][3]. Shaktism: Devotion to the Goddess (Devi/Shakti) in her many forms, including Durga, Kali, Lakshmi, and Saraswati. Particularly strong in Bengal and Assam [2][3]. Smartism: A tradition that worships five deities (Vishnu, Shiva, Shakti, Ganesha, Surya) as forms of one Brahman, often associated with Advaita Vedanta philosophy [2][3].

The six classical philosophical schools (Shad Darshanas), Samkhya, Yoga, Nyaya, Vaisheshika, Mimamsa, and Vedanta, represent different approaches to metaphysics, epistemology, and soteriology [2][3]. Modern Hindu movements include the Arya Samaj, Ramakrishna Mission, and various guru-led organizations [2][3].`,
  holidays: `Hindu festivals are numerous and vary significantly by region, tradition, and local custom [2][3]:

Diwali (October-November): The festival of lights, celebrating the triumph of light over darkness and good over evil. Associated with Lakshmi, Rama, and Krishna in different regions. Involves lighting oil lamps, fireworks, sweets, and family gatherings [2][3]. Holi (March): The festival of colors, marking the arrival of spring. Participants throw colored powders and water at each other in joyful celebration [2][3]. Navaratri/Durga Puja (September-October): Nine nights honoring the Goddess. Celebrated with dance (garba/dandiya) in Gujarat and elaborate pandal installations in Bengal [2][3]. Ganesh Chaturthi (August-September): Celebrates the birth of Ganesha, the elephant-headed god of beginnings. Particularly elaborate in Maharashtra [2][3]. Maha Shivaratri (February-March): The "Great Night of Shiva," observed with fasting, night vigils, and temple worship [2][3]. Janmashtami (August-September): Celebrates the birth of Krishna, with fasting, devotional singing, and dramatic reenactments of Krishna's life [2][3]. Pongal/Makar Sankranti (January): A harvest festival celebrated across South and North India under different names [2][3]. Kumbh Mela (every 12 years): A massive pilgrimage gathering at sacred river confluences, attracting tens of millions of participants [1][2][3].`,
  leadership: `Hinduism has no single centralized authority, pope, or governing body [2][3]. Religious leadership is distributed across multiple institutions and roles:

Gurus and Acharyas: Spiritual teachers who guide disciples in philosophical understanding and devotional practice. Some lead large organizations with millions of followers [2][3]. Shankaracharyas: The heads of the four mathas (monasteries) established by Adi Shankara in the 8th-9th century CE, considered authoritative voices in Advaita Vedanta [2][3]. Temple priests (pujaris/purohits): Conduct rituals and ceremonies at temples and for families. Brahmin priests traditionally perform Vedic rituals, though priestly roles vary by region and tradition [2][3]. Monastic orders (sannyasis): Renunciants who have taken vows of celibacy and poverty, dedicated to spiritual practice and teaching [2][3].

Modern Hindu organizations include the Vishva Hindu Parishad (VHP), the Ramakrishna Mission, ISKCON (International Society for Krishna Consciousness), and numerous ashrams and spiritual centers worldwide [2][3]. Political Hinduism (Hindutva) represents a nationalist movement distinct from religious Hinduism, though the boundaries are debated [2][3].`,
  symbols: `Hindu symbolism is rich and varied, reflecting the tradition's philosophical and devotional diversity [2][3]:

Om: The most sacred syllable in Hinduism, representing Brahman and the essence of the universe. It appears at the beginning of many prayers and mantras [2][3]. The lotus: Symbolizes purity, beauty, and spiritual awakening, as it grows from muddy water to bloom above the surface [2][3]. The swastika: An ancient symbol of auspiciousness and well-being in Hindu (and Buddhist and Jain) traditions, predating and entirely unrelated to its 20th-century misappropriation [2][3]. Tilaka: Marks applied to the forehead, varying by tradition, Vaishnavas typically use vertical lines, Shaivas use horizontal ash marks [2][3].

Deity iconography is central to Hindu visual culture. Ganesha (elephant-headed), Hanuman (monkey-faced), Nataraja (Shiva as cosmic dancer), and the many forms of the Goddess are among the most recognizable images [2][3]. Temple architecture follows elaborate symbolic programs, with the temple itself understood as a representation of the cosmos [2][3].`,
  keyFigures: `Hinduism's key figures span mythological, historical, and modern periods [2][3]:

Mythological and scriptural figures include Rama and Krishna (avatars of Vishnu and central characters of the epics), the sage Vyasa (traditionally credited with compiling the Vedas and composing the Mahabharata), and Valmiki (author of the Ramayana) [2][3].

Historical philosophers and teachers include Adi Shankara (788-820 CE), who systematized Advaita Vedanta; Ramanuja (1017-1137 CE), who developed Vishishtadvaita; and Madhva (1238-1317 CE), who articulated Dvaita Vedanta [2][3]. Medieval bhakti saints, including Kabir, Mirabai, Tulsidas, Chaitanya Mahaprabhu, and the Alvars and Nayanars of South India, transformed Hindu devotional practice through poetry, song, and social reform [2][3].

Modern figures include Ram Mohan Roy (1772-1833), a reformer who challenged practices like sati; Swami Vivekananda (1863-1902), who introduced Hindu philosophy to the West; Mahatma Gandhi (1869-1948), who drew on Hindu ethics in his philosophy of nonviolent resistance; and Sri Aurobindo (1872-1950), philosopher and spiritual teacher [2][3]. Contemporary gurus and teachers continue to shape Hindu practice globally [2][3].`,
  ethics: `Hindu ethics are grounded in the concepts of dharma, karma, and the pursuit of moksha [2][3]. Dharma, variously translated as duty, righteousness, moral law, or cosmic order, is the central ethical concept, though its specific requirements depend on one's social position, stage of life, and circumstances [2][3].

The concept of ahimsa (non-violence or non-harm) is an important ethical principle across Hindu traditions, influencing dietary practices (vegetarianism is widespread, particularly among Brahmins and Vaishnavas), attitudes toward animals, and social ethics [2][3]. Mahatma Gandhi elevated ahimsa to a political principle in his campaigns for Indian independence [2][3].

The Bhagavad Gita addresses ethical dilemmas through the dialogue between Arjuna and Krishna, exploring the tension between duty and compassion, action and renunciation [2][3]. Krishna's teaching that one should perform one's duty without attachment to results (nishkama karma) is a foundational ethical teaching [2][3].

The four purusharthas (aims of human life), dharma (righteousness), artha (prosperity), kama (pleasure), and moksha (liberation), provide a framework for balancing worldly and spiritual goals [2][3]. Hindu ethics also emphasize truthfulness (satya), self-control (dama), charity (dana), and compassion (daya) [2][3].`,
  afterlife: `Hindu beliefs about death and the afterlife center on the concepts of karma, samsara, and moksha [2][3].

Most Hindu traditions teach that the atman (soul or self) is eternal and undergoes a cycle of birth, death, and rebirth (samsara) [2][3]. The circumstances of each rebirth are determined by the accumulated karma, the moral consequences of one's actions in previous lives [2][3]. Rebirth can occur in various forms, including human, animal, or other states, depending on one's karma [2][3].

The ultimate goal in most Hindu traditions is moksha, liberation from the cycle of samsara [2][3]. Different schools describe moksha differently: Advaita Vedanta understands it as the realization that the individual self (atman) is identical with Brahman; Vishishtadvaita sees it as eternal communion with God; Dvaita Vedanta describes it as eternal closeness to but distinction from God [2][3].

Paths to moksha include jnana yoga (the path of knowledge), bhakti yoga (the path of devotion), karma yoga (the path of selfless action), and raja yoga (the path of meditation and discipline) [2][3]. The Bhagavad Gita discusses all four paths, suggesting they are complementary rather than mutually exclusive [2][3].

Funeral practices typically involve cremation, with the eldest son or closest male relative lighting the pyre [2][3]. Ashes are ideally immersed in a sacred river, particularly the Ganges. A mourning period follows, with rituals performed to assist the soul's transition [2][3].`,
  origins: `The origins of Hinduism are not traceable to a single founding event or figure but represent a long, layered process of cultural and religious development on the Indian subcontinent [2][3].

The earliest stratum is the Vedic period (c. 1500-500 BCE), associated with the Indo-Aryan peoples who composed the Vedas in Sanskrit [2][3]. Vedic religion centered on fire rituals (yajna), hymns to nature deities (Indra, Agni, Varuna), and a priestly class (Brahmins) who performed elaborate sacrificial ceremonies [2][3]. Some scholars also point to possible continuities with the earlier Indus Valley Civilization (c. 3300-1300 BCE), though the relationship remains debated [2][3].

The Upanishadic period (c. 800-200 BCE) saw a philosophical turn, with thinkers exploring concepts of Brahman, atman, karma, and moksha that would become central to later Hindu thought [2][3]. This period also saw the rise of the shramana movements, including Buddhism and Jainism, which challenged Vedic ritual authority and influenced Hindu development [2][3].

The classical and medieval periods (c. 200 BCE-1500 CE) witnessed the composition of the epics and Puranas, the development of temple-based worship, the systematization of philosophical schools, and the flowering of bhakti devotional movements that made Hindu practice accessible beyond the priestly elite [2][3]. The encounter with Islam from the 8th century CE onward and with European colonialism from the 16th century further shaped Hindu traditions [2][3].

Modern Hinduism has been influenced by reform movements (Brahmo Samaj, Arya Samaj), the independence movement, and globalization, which has spread Hindu practices like yoga worldwide [2][3].`,
  sourceSix: 'Ralph T.H. Griffith translations of Vedic texts (late 19th century), public domain editions.',
  sourceSixUrl: 'https://sacred-texts.com/hin/',
};
