import type { EtiquetteGuideSeed } from '@/lib/resource-details/etiquette-guide-types';

export const ETIQUETTE_GUIDE_SEEDS_A: EtiquetteGuideSeed[] = [
  {
    title: 'Visiting a Church Respectfully',
    tradition: 'Christianity',
    setting: 'churches and parish spaces',
    summaryFocus: 'dress, service flow, communion boundaries, and quiet behavior during prayer',
    wearRequired: ['clean everyday clothing', 'covered shoulders and midriff', 'trousers, jeans, or skirts that reach at least the knee', 'layers you can sit and stand in comfortably'],
    wearAvoid: ['beachwear', 'very short shorts', 'shirts with profanity or alcohol branding', 'hats that block the view during worship'],
    wearNotes: 'Most churches do not require formal clothing, but they do expect visitors to look like they came to join a solemn gathering rather than a sporting event. In older parishes and cathedrals, people often dress one step more formally than they would for casual errands, especially at weddings, funerals, Christmas, Easter, and evening concerts.',
    bringHelpful: ['a silent phone', 'a small bill for the offering basket if you want to contribute', 'reading glasses if you use them', 'a light jacket if the building is cool'],
    bringAvoid: ['food in the sanctuary', 'open drinks', 'large shopping bags', 'anything noisy on a keychain or bag strap'],
    bringNotes: 'Many churches hand out a printed bulletin at the door, so you usually do not need to bring your own materials. If the church uses hymnals or printed liturgy, an usher will normally place one in your hand or point you to the rack. Keep bags tucked under your seat or beside your feet so aisles stay clear when people stand to pray or move toward communion.',
    arrivalWindow: '10 to 15 minutes before the service starts',
    arrivalTimingDetails: 'That window gives you enough time to find parking, meet an usher, choose a seat, and learn whether the church has any visitor guidance about communion, children, or photography. Arriving exactly at the start can force you to walk down the aisle during the opening prayer or hymn.',
    arrivalFlow: 'At most churches, a greeter or usher meets visitors at the entrance, offers a bulletin, and may ask whether you want nursery directions or help finding a seat. If no one approaches you, pause near the back for a moment and watch where regular attendees place coats, bags, and strollers before you move deeper into the room.',
    whatHappens: ['an opening greeting or hymn', 'scripture readings', 'prayers led by clergy or the congregation', 'a sermon or homily', 'announcements and an offering collection in many communities', 'communion or a closing blessing in many services'],
    whatHappensNotes: 'People usually sit, stand, or kneel together, but the exact sequence varies by denomination. In liturgical churches the congregation may recite printed responses. In less formal churches there may be more music, spontaneous prayer, and a longer sermon. Watch the first row or the ushers if you are unsure when to stand. The safest choice is to follow the room without drawing attention to yourself.',
    participationDo: ['stand and sit with the congregation', 'sing softly if you know the hymn or can follow the words', 'join spoken responses that are printed in the bulletin', 'offer a handshake during the peace or greeting time if others are doing the same'],
    participationAvoid: ['take communion without first learning the church policy', 'walk around during prayer', 'talk loudly once worship has started', 'step into the altar area or onto the platform without invitation'],
    participationNotes: 'Communion is the main boundary visitors need to respect. Some churches invite all baptized Christians, some invite anyone seeking Christ, and some restrict communion to members or those in full sacramental standing. If you do not know the rule, remain seated or ask an usher before the service. That choice is more respectful than guessing.',
    commonMistakes: ['sliding into a front pew after the prayer has already begun', 'treating the sanctuary like a museum', 'taking flash photos during worship', 'assuming communion is always open to visitors', 'letting children run the aisles during the sermon', 'leaving immediately after an usher has started the closing prayer'],
    phrases: [
      { phrase: 'Good morning', meaning: 'a simple greeting that fits almost every church setting', whenToUse: 'you greet greeters, ushers, and people seated near you before the service begins' },
      { phrase: 'Peace be with you', meaning: 'a common Christian exchange during worship', whenToUse: 'the congregation is already exchanging it during the service' },
      { phrase: 'Amen', meaning: 'so be it, or a spoken sign of agreement in prayer', whenToUse: 'the congregation says it at the end of prayers' },
    ],
    phraseNotes: 'You do not need insider language to be respectful in a church. Simple, quiet courtesy works well. If a congregation uses a printed liturgy, the bulletin usually shows exactly what the people say together, so reading from the page is better than improvising.',
    relatedLinks: [
      { label: 'Christianity profile', href: '/religions/christianity' },
      { label: 'Christianity reading list', href: '/recommended-reading/christianity' },
    ],
  },
  {
    title: 'Visiting a Catholic Mass Respectfully',
    tradition: 'Catholicism',
    setting: 'Catholic parishes and cathedrals',
    summaryFocus: 'Mass posture, reverence for the Eucharist, dress expectations, and how visitors should handle communion',
    wearRequired: ['modest clothing that covers shoulders, chest, and knees', 'closed-toe or quiet shoes', 'layers that let you stand, sit, and kneel', 'more formal clothes for holy days, funerals, or cathedral visits'],
    wearAvoid: ['short shorts', 'strapless tops', 'transparent fabrics', 'shirts with crude slogans'],
    wearNotes: 'Catholic parishes vary by region, but the safer standard is neat, modest clothing that would not distract during prayer. In tourist-heavy cathedrals, staff may refuse entry to visitors wearing bare shoulders or very short clothing, even if they would be admitted to an ordinary parish on a weekday.',
    bringHelpful: ['a silent phone', 'a small donation if you want to contribute', 'a missal app only if the parish permits phones before Mass starts', 'a shawl or sweater in colder stone churches'],
    bringAvoid: ['food or coffee in the nave', 'large backpacks in crowded cathedrals', 'selfie sticks', 'anything that will rattle when people kneel'],
    bringNotes: 'Many parishes provide a worship aid with the readings and responses. If you use your phone for the liturgy, turn it off completely once Mass begins. A lit screen during the consecration is more distracting than many visitors realize. Keep your belongings compact because Catholic worship includes kneeling and standing in close rows.',
    arrivalWindow: '15 minutes before Mass, or 25 minutes before a major feast or Sunday cathedral liturgy',
    arrivalTimingDetails: 'That extra time matters because many Catholics pray silently before Mass, light candles, or line up for confession beforehand. If you arrive early, you can settle in without cutting through a pew once the entrance procession has begun.',
    arrivalFlow: 'On entry, some Catholics dip a hand into holy water and make the sign of the cross. Visitors are not required to do this. Before sitting, many Catholics genuflect toward the tabernacle or bow toward the altar. If you are unsure, a simple respectful pause is better than copying a gesture you do not understand.',
    whatHappens: ['an entrance procession', 'opening prayers and readings from scripture', 'a homily', 'the Creed and prayers of the faithful on many Sundays', 'the Liturgy of the Eucharist, including the consecration of bread and wine', 'communion and a closing blessing'],
    whatHappensNotes: 'Mass has a regular structure, and the congregation often stands, sits, and kneels together. Bells may ring during the consecration. Silence matters most during the readings, the Eucharistic Prayer, and after communion. In cathedrals and solemn feasts there may also be incense, chanting, and longer processions.',
    participationDo: ['follow the congregation in standing and sitting', 'kneel if you are physically able and comfortable doing so, or remain seated respectfully', 'join spoken responses from the printed worship aid', 'approach an usher before Mass if you have questions about local custom'],
    participationAvoid: ['receive communion unless you know you are invited under Catholic discipline', 'enter the communion line just to avoid standing out', 'talk during the Eucharistic Prayer', 'wander into side chapels that are marked for private prayer during Mass'],
    participationNotes: 'For most non-Catholic visitors, the clearest respectful choice is to remain in the pew during communion. In some parishes people with arms crossed receive a blessing, but that custom is not universal, so you should not assume it is expected everywhere. Catholics treat the Eucharist as the real presence of Christ, so this is the center of the service, not a symbolic snack line.',
    commonMistakes: ['taking photos during the consecration', 'sitting in the aisle seat and forcing a whole pew to move during communion', 'mistaking a cathedral for a sightseeing site during worship hours', 'chewing gum in the pews', 'copying the sign of peace too loudly or too casually', 'ignoring kneelers and dropping bags where people need to kneel'],
    phrases: [
      { phrase: 'Peace be with you', meaning: 'a formal liturgical greeting exchanged during Mass', whenToUse: 'the congregation is exchanging the sign of peace' },
      { phrase: 'And with your spirit', meaning: 'the standard congregational response to the priest in English Mass', whenToUse: 'you are following the spoken responses from the worship aid' },
      { phrase: 'Amen', meaning: 'a liturgical sign of assent at the end of prayer', whenToUse: 'the congregation reaches the end of a shared prayer' },
    ],
    phraseNotes: 'Catholic liturgy is printed and structured, so visitors do not need to improvise. If you are not sure whether to speak, silence is fine. If you do speak, use the exact printed response instead of paraphrasing from memory.',
    relatedLinks: [
      { label: 'Catholicism profile', href: '/religions/catholicism' },
      { label: 'Compare Catholicism vs Protestantism', href: '/compare/catholicism-vs-protestantism' },
    ],
  },
  {
    title: 'Visiting an Orthodox Church Respectfully',
    tradition: 'Orthodox Christianity',
    setting: 'Orthodox churches and monasteries',
    summaryFocus: 'icon veneration, standing worship, modest clothing, incense, and strict Eucharistic boundaries',
    wearRequired: ['modest clothing that covers shoulders, chest, and knees', 'closed shoes', 'a longer skirt and headscarf for women in stricter monasteries', 'trousers and sleeves for men'],
    wearAvoid: ['shorts', 'sleeveless tops', 'tight athletic wear', 'loud prints that stand out in a prayerful setting'],
    wearNotes: 'Orthodox churches often expect a more traditional standard of modesty than many Western churches. Monasteries can be stricter still. If you are visiting a monastery, assume that women may need a headscarf and long skirt, and men may be turned away for shorts or sleeveless shirts even in hot weather.',
    bringHelpful: ['a silent phone', 'cash for candles if the church offers them', 'a scarf if you are a woman visiting a conservative parish', 'a small notebook only for use outside the service'],
    bringAvoid: ['coffee in the nave', 'flash cameras', 'bulky bags', 'food unless a host explicitly gives it to you afterward'],
    bringNotes: 'If the parish has a candle stand, many visitors light a candle on arrival. Do this only after watching how the local community handles it. In some churches a helper will show you where to place the candle and whether you should kiss an icon first. Keep your hands free because Orthodox spaces are visually dense, and you do not want to juggle bags while people move to venerate icons.',
    arrivalWindow: '20 minutes before the Divine Liturgy, and earlier for monasteries or major feast days',
    arrivalTimingDetails: 'Orthodox worship often begins quietly before the formal liturgy, and many regulars arrive early to light candles, kiss icons, and pray before taking their place. Arriving late can mean walking through moving lines of worshippers or through incense-filled processions.',
    arrivalFlow: 'You may enter a vestibule first, then pass into the main nave facing the iconostasis, the icon screen before the altar. Some people kiss icons near the entrance, then move to a candle stand, then take a place near a wall or in an open section. Seating may be limited, because standing is common in many parishes.',
    whatHappens: ['chanting rather than spoken recitation for much of the service', 'incense censed through the church', 'frequent signs of the cross and bows from worshippers', 'the reading of scripture and a sermon', 'the Divine Liturgy centered on the Eucharist', 'distribution of blessed bread after the service in some parishes'],
    whatHappensNotes: 'Orthodox services are sensory, with icons, candles, incense, and sustained chanting. People may enter and leave briefly to light candles even after worship has begun, so the movement pattern can look less fixed than in a Roman Catholic parish. Still, the altar area remains highly restricted, and the Eucharist is reserved for prepared Orthodox faithful.',
    participationDo: ['stand quietly near the back or side if seating is scarce', 'sit when clearly needed for health or age', 'observe icon veneration before attempting it yourself', 'accept blessed bread after the liturgy only if a host offers it and tells you how'],
    participationAvoid: ['receive the Eucharist', 'cross your legs in a tight seating area where it blocks others', 'walk directly in front of people venerating icons', 'touch icons, vessels, or the iconostasis casually'],
    participationNotes: 'If you want to kiss an icon, first ask someone to show you the local pattern because there is often an order to how people bow, cross themselves, and move. If you do not know the order, respectful observation is enough. The main thing is to avoid treating devotional acts as tourist experiences.',
    commonMistakes: ['treating the iconostasis like a photo backdrop', 'assuming every Orthodox parish has pews', 'taking incense and chanting as a performance rather than worship', 'joining the communion line because others are moving', 'wearing monastery-inappropriate clothing', 'talking in the nave after the priest has started the blessing'],
    phrases: [
      { phrase: 'Father, bless', meaning: 'a respectful way to address a priest in some Orthodox settings', whenToUse: 'local parishioners are clearly doing so, otherwise use a normal greeting' },
      { phrase: 'Lord, have mercy', meaning: 'a repeated liturgical prayer in Orthodox worship', whenToUse: 'you can follow the congregation or printed text' },
      { phrase: 'Christ is risen', meaning: 'a seasonal Easter greeting in many Orthodox communities', whenToUse: 'the parish is already using it during Pascha season' },
    ],
    phraseNotes: 'Orthodox worship has strong inherited patterns. It is better to speak little and follow carefully than to overperform familiarity. If you are welcomed at coffee hour afterward, that is usually the best time to ask questions.',
    relatedLinks: [
      { label: 'Orthodox Christianity profile', href: '/religions/orthodox-christianity' },
      { label: 'Orthodox reading list', href: '/recommended-reading/orthodox-christianity' },
    ],
  },
  {
    title: 'Visiting a Protestant Church Respectfully',
    tradition: 'Protestantism',
    setting: 'Protestant churches and chapels',
    summaryFocus: 'service style differences, music, sermon-focused worship, and local communion practice',
    wearRequired: ['clean everyday clothing', 'comfortable shoes', 'modest tops and bottoms', 'layers for air-conditioned or heated auditoriums'],
    wearAvoid: ['extremely revealing clothing', 'shirts with insulting messages', 'anything that would distract in a quiet prayer setting', 'hats that block others if seating is tight'],
    wearNotes: 'Protestant churches range from suit-and-tie congregations to churches where people wear jeans and sneakers. The safest choice is neat, modest, middle-ground clothing. If the church livestreams the service, remember that you may be seen on camera while entering or greeting people.',
    bringHelpful: ['a silent phone', 'a Bible if you already use one', 'a notebook if the church encourages sermon notes', 'a small donation if you want to participate in the offering'],
    bringAvoid: ['open drinks in the worship space', 'noisy wrappers', 'oversized bags that block seating', 'flash photography gear'],
    bringNotes: 'Many Protestant churches project lyrics and sermon outlines on screens, so visitors often need less printed material than in liturgical traditions. Still, keep your phone silent and your possessions simple. In churches with café lobbies, finish drinks before entering the sanctuary unless the local custom clearly permits them inside.',
    arrivalWindow: '10 to 15 minutes before the service, and 20 minutes before a large Sunday gathering',
    arrivalTimingDetails: 'Arriving a little early gives you time to ask whether the service includes communion, a greeting time, children dismissal, or reserved family seating. In some congregations the music begins right at the announced start time, so late entry becomes very visible.',
    arrivalFlow: 'Greeters may welcome you at the door, hand you a bulletin, and ask if you are new. Some churches ask visitors to fill out a card, but this is usually optional. If the church has a fellowship hall or coffee station, do not assume you need to socialize there before worship. Going straight to your seat is perfectly acceptable.',
    whatHappens: ['opening songs or hymns', 'welcome and announcements', 'scripture reading', 'a sermon, often the longest central element', 'prayer and sometimes an offering collection', 'communion in some churches, or an altar call in some evangelical settings'],
    whatHappensNotes: 'The sermon often shapes the whole rhythm of the service, so listening well matters more than mastering ritual responses. Some congregations stand for music, others remain seated. Some are highly informal and use contemporary bands, while others follow a printed order with choir, organ, and set prayers.',
    participationDo: ['stand and sing if you are comfortable', 'remain seated quietly if you do not know the songs', 'follow printed or projected readings', 'ask a greeter before the service if communion is open to visitors'],
    participationAvoid: ['assume every Protestant church has the same view of communion', 'treat the sermon like a lecture hall talk and whisper through it', 'wander in and out during prayer', 'walk onto the stage or into backstage musician areas'],
    participationNotes: 'Communion practice varies sharply. Some churches pass trays in the pews, some invite people forward, and some celebrate communion only on certain Sundays. If the church has a response time at the end, visitors are not required to go forward. Remaining in your seat is normal and respectful.',
    commonMistakes: ['assuming music volume means silence no longer matters', 'thinking casual dress means casual behavior', 'taking photos of the worship team during prayer', 'treating altar calls like a spectator moment', 'letting children roam the front while the pastor is preaching', 'mistaking a greeting time for an invitation to start long conversations'],
    phrases: [
      { phrase: 'Good morning', meaning: 'a simple and appropriate greeting in almost every Protestant setting', whenToUse: 'you greet greeters, ushers, or the people seated around you' },
      { phrase: 'Peace be with you', meaning: 'a greeting used in some liturgical Protestant churches', whenToUse: 'the congregation is already exchanging it' },
      { phrase: 'Amen', meaning: 'a brief spoken agreement at the end of prayer', whenToUse: 'the congregation says it together' },
    ],
    phraseNotes: 'You do not need insider church language to fit in. In most Protestant congregations, warmth, eye contact, and a simple thank you to the greeters matter more than special formulas.',
    relatedLinks: [
      { label: 'Protestantism profile', href: '/religions/protestantism' },
      { label: 'Compare Protestantism vs Orthodox Christianity', href: '/compare/protestantism-vs-orthodox-christianity' },
    ],
  },
  {
    title: 'Visiting a Mosque Respectfully',
    tradition: 'Islam',
    setting: 'mosques and Islamic centers',
    summaryFocus: 'modest clothing, shoe removal, prayer-row etiquette, Friday Jumuah expectations, and respectful greetings',
    wearRequired: ['long sleeves', 'loose trousers or an ankle-length skirt or dress', 'clothing that covers shoulders, chest, and knees', 'a headscarf for women in communities that expect it', 'socks if you prefer not to walk barefoot after removing shoes'],
    wearAvoid: ['shorts', 'tank tops', 'tight leggings without a long top', 'sheer fabric', 'clothes with alcohol or profanity graphics'],
    wearNotes: 'At many mosques, men and women enter through different doors or move to separate prayer areas, so dress before arrival instead of trying to fix clothing in the lobby. Women who do not normally cover their hair should carry a plain scarf. Men should not wear sleeveless gym clothing or beachwear. Fragrance should be light, because crowded prayer lines make strong perfume noticeable immediately.',
    bringHelpful: ['a plain scarf if you are a woman', 'a silent phone', 'a small pair of clean socks', 'a modest donation if the mosque has a donation box'],
    bringAvoid: ['food or drinks in the prayer hall', 'large backpacks', 'pets other than service animals', 'flash photography equipment'],
    bringNotes: 'Shoes come off at the door or just before the carpeted prayer area, so choose footwear you can remove quickly and place neatly on the rack or shelf. If the mosque lends robes or head coverings, use them gratefully and return them folded. Keep keys, coins, and phones tucked away, because hard floors and quiet rooms make every dropped item sound louder than you expect.',
    arrivalWindow: '15 to 20 minutes before a daily prayer, and 25 to 30 minutes before Friday Jumuah',
    arrivalTimingDetails: 'Friday is the main weekly congregation, so parking fills sooner, the sermon begins before the congregational prayer, and late arrivals create more disruption than on ordinary days. If you are visiting on Friday, assume the building will be busier, lines at the shoe area will move slower, and volunteers will appreciate brief questions asked before the khutbah begins.',
    arrivalFlow: 'Many mosques have a foyer, shoe area, ablution space, and then the main prayer hall. Guests are often shown to a side wall or rear section first so they can observe without crossing active rows of worshippers. If a volunteer asks whether you need the brothers section or sisters section, answer briefly and let them guide you rather than choosing a doorway on your own.',
    whatHappens: ['shoes being removed at the entrance', 'worshippers lining up shoulder to shoulder facing the qibla, toward Mecca', 'short cycles of standing, bowing, prostrating, and sitting during salah', 'the adhan, the call to prayer, in some services', 'a sermon, called a khutbah, before the Friday congregational prayer', 'men and women praying in separate rooms or separate sections in many communities'],
    whatHappensNotes: 'You may also see worshippers performing wudu, ritual washing, before entering the prayer space. During Friday prayer, conversation should stop once the khutbah begins. Children may be present, but the overall tone remains orderly and quiet. The prayer hall is not a sightseeing room. It is a working sacred space organized around the prayer rows and the direction of prayer.',
    participationDo: ['greet hosts with As-salamu alaykum if you are comfortable doing so', 'sit or stand where a host places you', 'watch prayer movements without copying them if you are unsure', 'ask questions after the prayer has ended'],
    participationAvoid: ['walk directly in front of someone who is praying', 'step onto the carpet with shoes', 'attempt to join the prayer line unless invited and instructed', 'offer a handshake to someone of the opposite sex if they are clearly avoiding physical contact'],
    participationNotes: 'If someone offers a handshake, return it politely. If they place a hand on their chest instead, mirror that gesture and smile. During prayer, keep still, keep your phone out of sight, and do not whisper, film, or wander through the rows. If you need to move, walk behind the last row of worshippers, never between a person and the direction of prayer.',
    commonMistakes: ['arriving in shorts or sleeveless tops', 'leaving shoes in the doorway instead of on the rack', 'wandering into the front rows for a better view', 'taking photos during prayer', 'crossing in front of a worshipper', 'bringing coffee or snacks into the prayer hall'],
    phrases: [
      { phrase: 'As-salamu alaykum', meaning: 'peace be upon you', whenToUse: 'you greet a host or volunteer if you are comfortable saying it' },
      { phrase: 'Wa alaykum as-salam', meaning: 'and peace be upon you', whenToUse: 'someone greets you first' },
      { phrase: 'Jazak Allahu khayran', meaning: 'may God reward you with goodness', whenToUse: 'you want to thank someone who has helped you' },
    ],
    phraseNotes: 'You do not need Arabic to be respectful, but these phrases are common and easy to use kindly. Speak slowly, and do not worry about perfect pronunciation. In many mosques, a warm smile and quiet tone matter more than sounding expert.',
    relatedLinks: [
      { label: 'Islam profile', href: '/religions/islam' },
      { label: 'Islam reading list', href: '/recommended-reading/islam' },
    ],
  },
];
