import type { EtiquetteGuideSeed } from '@/lib/resource-details/etiquette-guide-types';

export const ETIQUETTE_GUIDE_SEEDS_D: EtiquetteGuideSeed[] = [
  {
    title: 'Visiting a Baha’i House of Worship Respectfully',
    tradition: 'Baha’i Faith',
    setting: 'Baha’i temples and devotional spaces',
    summaryFocus: 'quiet reflection, modest dress, non-disruptive interfaith attendance, and reverent behavior in a prayer-centered environment',
    wearRequired: ['modest everyday clothing', 'quiet shoes', 'covered shoulders and knees', 'simple clothing that suits a meditative setting'],
    wearAvoid: ['beachwear', 'loud slogans', 'revealing outfits', 'anything that signals you are treating the temple like a tourist attraction'],
    wearNotes: 'Baha’i Houses of Worship are open to people of all backgrounds, but openness does not mean casualness. Dress should communicate that you are entering a place set apart for prayer, contemplation, and unity. Clothing does not need to be formal, but it should never compete with the atmosphere of stillness.',
    bringHelpful: ['a silent phone', 'a light layer in case the interior is cool', 'a small bag that stays tucked away', 'a respectful willingness to sit quietly for a time'],
    bringAvoid: ['food or drinks in the prayer space', 'banners, signs, or promotional materials', 'camera gear for staged photography', 'anything noisy or distracting'],
    bringNotes: 'Baha’i devotional spaces are often architecturally beautiful, which can tempt visitors to treat them like scenic attractions. Keep your belongings minimal so the visit remains about prayerful presence rather than setup, filming, or display. If the site has a visitor center, save informational conversations for there rather than carrying them into the sanctuary.',
    arrivalWindow: '10 to 15 minutes before a devotional program, or any quiet period if you are visiting for private reflection',
    arrivalTimingDetails: 'Arriving a little early gives you time to notice whether the sanctuary is already silent, whether shoes stay on, and whether a reading or musical program is about to begin. This helps you enter without turning heads or crossing the room after everyone is settled.',
    arrivalFlow: 'Many Baha’i Houses of Worship have a transition from outdoor grounds to a central prayer space. Visitors usually enter quietly, choose a seat, and let the stillness set the tone. If a host is present, they may explain whether the current period is silent prayer, a devotional gathering, or general visiting hours.',
    whatHappens: ['quiet seated reflection', 'readings from sacred writings in some programs', 'devotional music or singing without performance theatrics', 'periods of shared silence', 'interfaith attendance without pressure to belong formally', 'careful movement in and out of the sanctuary'],
    whatHappensNotes: 'A Baha’i House of Worship is not centered on spectacle or a highly choreographed ritual sequence. Its emphasis is devotion, unity, and reverence. That means the visitor’s main task is simple: keep the room calm. If a program is happening, follow the rhythm without adding side conversation, unnecessary movement, or visible device use.',
    participationDo: ['sit quietly', 'listen respectfully to readings or music', 'remain in silence if that is the local norm', 'ask practical questions outside the sanctuary'],
    participationAvoid: ['treat the sanctuary like a tour stop', 'speak loudly in the prayer area', 'photograph people in devotion without permission', 'introduce sectarian debate into a prayer gathering'],
    participationNotes: 'Visitors are welcome in Baha’i spaces because the tradition emphasizes human unity, but that welcome is best honored through restraint. You do not need to perform devotion outwardly. Being still, attentive, and non-disruptive is already a meaningful form of respect.',
    commonMistakes: ['whispering through a silent period because the room feels open and informal', 'using a temple visit mainly for photography', 'asking doctrinal questions in the sanctuary itself', 'bringing drinks into the prayer area', 'mistaking openness for casual behavior', 'moving seats repeatedly during readings or music'],
    phrases: [
      { phrase: 'Hello', meaning: 'a simple greeting is entirely appropriate', whenToUse: 'you meet a host or volunteer at the entrance' },
      { phrase: 'Thank you', meaning: 'a respectful expression of gratitude', whenToUse: 'someone explains the space or answers a question' },
      { phrase: 'Devotional', meaning: 'a gathering centered on prayer and readings', whenToUse: 'you are clarifying what kind of program is happening' },
    ],
    phraseNotes: 'You do not need specialized Baha’i vocabulary to behave well in a House of Worship. Plain courtesy and silence fit the setting naturally. The architecture may be famous, but the room is still for prayer first.',
    relatedLinks: [
      { label: 'Baha’i Faith profile', href: '/religions/bahai-faith' },
      { label: 'Baha’i reading list', href: '/recommended-reading/bahai-faith' },
    ],
  },
  {
    title: 'Visiting a Taoist Temple Respectfully',
    tradition: 'Taoism',
    setting: 'Taoist temples and ritual halls',
    summaryFocus: 'incense use, offerings, ritual specialist boundaries, and respectful movement through active devotional space',
    wearRequired: ['modest clothing', 'comfortable shoes that can handle temple courtyards and stairs', 'covered shoulders and knees', 'simple layers for indoor and outdoor spaces'],
    wearAvoid: ['very revealing outfits', 'costume-like clothing', 'anything that interferes with incense-heavy settings', 'shoes that make fast, noisy movement necessary'],
    wearNotes: 'Taoist temples often combine active devotion, ritual implements, incense, and multiple altars within one site. Clothing should let you move carefully through courtyards and halls without brushing altars, lamps, or other visitors. Modesty and practicality matter more than trying to look traditional.',
    bringHelpful: ['a silent phone', 'small cash for an offering box if appropriate', 'minimal belongings', 'a tissue or handkerchief for incense-heavy environments'],
    bringAvoid: ['food near altars', 'large bags that swing into ritual objects', 'casual touching of temple implements', 'tripods or lighting equipment'],
    bringNotes: 'Temples sometimes sell approved incense or offering items on site. If so, use those rather than bringing your own objects and deciding independently where they belong. Taoist ritual spaces can be dense with symbolic tools, paper items, and altar arrangements, so carrying less is often the most respectful choice.',
    arrivalWindow: '10 to 20 minutes before a public rite, or at a calm time if you are visiting the temple outside formal ceremony',
    arrivalTimingDetails: 'Early arrival is useful because temple layout can be complex. You may need a moment to see which hall is active, where incense is being offered, and whether a ritual specialist is leading a service that should not be interrupted by wandering visitors.',
    arrivalFlow: 'You may move from an outer gate into courtyards and then toward one or more inner halls. Watch whether worshippers stop first at a main altar, light incense in a designated place, or bow before entering a hall. If a priest or ritual specialist is working, do not walk close behind them or crowd the altar to get a better look.',
    whatHappens: ['offerings of incense at designated points', 'bows or quiet pauses before altars', 'movement through multiple halls or shrines', 'ritual chanting or liturgical recitation at some times', 'priests performing rites at altars', 'purchase of approved offerings, charms, or paper items in some temples'],
    whatHappensNotes: 'Taoist temple life can blend devotional, ritual, and practical elements. That can make the space look flexible, but it still has boundaries. Altars are not display tables, incense burners are not casual props, and priests are not tour guides while they are officiating. The respectful visitor lets ritual work proceed without stepping into it.',
    participationDo: ['watch where worshippers place incense before doing the same', 'follow marked pathways', 'pause quietly at altars', 'ask a staff member before making any offering if the process is unclear'],
    participationAvoid: ['touch ritual swords, registers, bells, or other implements', 'place incense or offerings wherever you choose', 'block a priest during a rite', 'treat smoke, chants, or altar items as performance props'],
    participationNotes: 'If you choose to offer incense, do it with slow, careful attention and in the place the temple designates. If you are not sure, observing is better than guessing. Taoist ritual often relies on order, placement, and sequence, so improvisation from visitors can be genuinely disruptive.',
    commonMistakes: ['lighting incense in the wrong place', 'walking too close to an active altar', 'taking elaborate photos during ritual', 'touching temple objects for luck or novelty', 'speaking over chanting because the room seems busy', 'assuming all East Asian temple customs are interchangeable'],
    phrases: [
      { phrase: 'Ni hao', meaning: 'hello in Mandarin', whenToUse: 'you greet staff in a Chinese-speaking temple setting' },
      { phrase: 'Incense', meaning: 'the offering material most visitors will notice first', whenToUse: 'you are politely asking where it should be placed' },
      { phrase: 'Thank you', meaning: 'plain gratitude is often the safest choice', whenToUse: 'someone shows you the correct route or altar etiquette' },
    ],
    phraseNotes: 'Local language and custom vary widely in Taoist communities. The key phrase is often a quiet thank you after guidance. Showing that you will follow directions matters more than knowing specialized vocabulary.',
    relatedLinks: [
      { label: 'Taoism profile', href: '/religions/taoism' },
      { label: 'Taoism reading list', href: '/recommended-reading/taoism' },
    ],
  },
  {
    title: 'Visiting a Confucian Temple Respectfully',
    tradition: 'Confucianism',
    setting: 'Confucian temples and memorial complexes',
    summaryFocus: 'ceremonial decorum, educational memory, respectful movement, and how to handle a site that may be devotional, historical, and civic at once',
    wearRequired: ['modest, tidy clothing', 'comfortable shoes suitable for courtyards and ceremonial grounds', 'weather-appropriate layers', 'clean, understated attire'],
    wearAvoid: ['partywear', 'very casual gym clothing', 'loud slogans', 'anything that turns a memorial site into a personal performance space'],
    wearNotes: 'Confucian temples may feel more like ceremonial or memorial complexes than congregational worship spaces, but that does not make etiquette less important. These sites often honor learning, ritual propriety, and reverence for sages and ancestors. Dress should reflect seriousness and order, not spectacle.',
    bringHelpful: ['a silent phone', 'water kept outside interior ceremonial spaces', 'a small notebook for use outside formal halls', 'minimal personal belongings'],
    bringAvoid: ['food in ceremonial halls', 'loud audio guides on speaker', 'staged photo props', 'objects placed on memorial tablets or platforms'],
    bringNotes: 'Because some Confucian temples function partly as heritage sites, visitors sometimes misread them as museums with no behavioral expectations. That is a mistake. Keep belongings light and controlled, and remember that ceremonial halls and memorial tablets should never be treated as display furniture or leaning points.',
    arrivalWindow: '10 to 15 minutes before a ceremony, lecture, or guided ritual event, or any calm period for ordinary visiting',
    arrivalTimingDetails: 'If a formal rite or educational program is scheduled, early arrival helps you identify where observers stand and which spaces are reserved. In more open hours, timing matters less, but a slow arrival still helps you read the atmosphere before crossing central courtyards or entering main halls.',
    arrivalFlow: 'Visitors often move through gates into a sequence of courtyards and halls. Some areas may be open for quiet viewing, while others are reserved for ceremony. Watch signs closely, especially near the main hall and any spaces displaying memorial tablets, ceremonial instruments, or ritual vessels. If a formal event is beginning, staff may place guests along the sides rather than in the center axis.',
    whatHappens: ['quiet walking through formal courtyards', 'viewing memorial or teaching halls', 'ritual bows in some ceremonies', 'lectures, commemorations, or educational programs at some sites', 'limited access to central ceremonial areas during rites', 'a strong visual emphasis on order, symmetry, and decorum'],
    whatHappensNotes: 'In a Confucian setting, ritual order and dignified behavior can matter as much as verbal prayer. The site may be partly historical, but it still teaches through posture, sequence, and restraint. Visitors should take cues from this rather than trying to animate the space with loud commentary or elaborate photography.',
    participationDo: ['walk calmly', 'read signage before entering a hall', 'stand aside during ceremonies', 'ask staff where observers belong if an event is underway'],
    participationAvoid: ['sit on ceremonial platforms', 'cross central ceremonial paths during a rite', 'touch memorial tablets or instruments', 'treat the grounds like an amusement backdrop'],
    participationNotes: 'If a bow or moment of silence is part of the program, simple participation is usually better than theatrical imitation. In Confucian contexts, propriety often means doing less, with more control. Let the architecture and ceremony lead your behavior.',
    commonMistakes: ['assuming a heritage site has no sacred or ceremonial dimension', 'climbing onto steps or platforms for photos', 'talking loudly inside memorial halls', 'ignoring roped-off ceremonial zones', 'touching instruments or tablets', 'walking through the exact center of an active ceremony because it seems like the best sightline'],
    phrases: [
      { phrase: 'Ni hao', meaning: 'hello in Mandarin', whenToUse: 'you greet staff in a Chinese-speaking setting' },
      { phrase: 'Temple office', meaning: 'the place where staff can clarify access or ceremony timing', whenToUse: 'you need practical guidance rather than guessing' },
      { phrase: 'Thank you', meaning: 'plain gratitude is often best', whenToUse: 'staff explain where visitors should stand or walk' },
    ],
    phraseNotes: 'Confucian etiquette is often less about special phrases and more about visible self-control. Read the signs, walk slowly, and let staff direct you if a ceremony is in progress.',
    relatedLinks: [
      { label: 'Confucianism profile', href: '/religions/confucianism' },
      { label: 'Confucianism reading list', href: '/recommended-reading/confucianism' },
    ],
  },
  {
    title: 'Visiting a Zoroastrian Fire Temple Respectfully',
    tradition: 'Zoroastrianism',
    setting: 'fire temples and community precincts',
    summaryFocus: 'entry boundaries, reverence for sacred fire, purity rules, and how visitors should honor spaces they may not be permitted to enter',
    wearRequired: ['modest clothing that covers shoulders and knees', 'clean garments', 'quiet shoes', 'simple, non-distracting attire'],
    wearAvoid: ['revealing clothing', 'beachwear', 'anything dirty or sloppy', 'assumptions that tourist clothing is acceptable for a ritual precinct'],
    wearNotes: 'Zoroastrian communities often place strong emphasis on purity, order, and respect around the sacred fire. Even before you know whether entry is possible, dress as if the answer may be no and your first obligation is to honor the boundary gracefully. Cleanliness matters, and a restrained appearance helps signal that you understand the seriousness of the place.',
    bringHelpful: ['a silent phone', 'minimal belongings', 'a respectful willingness to remain outside interior spaces if required', 'cash only if the community has a public donation option'],
    bringAvoid: ['food or drinks near sacred areas', 'camera gear for interior photography', 'large bags', 'pressure to negotiate access once a boundary has been stated'],
    bringNotes: 'Many Zoroastrian fire temples restrict entry to practicing Zoroastrians, especially in the innermost ritual areas. That means the respectful visitor arrives ready to accept a no without frustration. If there is a public-facing courtyard, office, or educational area, keep belongings discreet and never assume that public grounds imply access to the sanctum.',
    arrivalWindow: '10 to 15 minutes before any scheduled public-facing meeting, or during posted visitor hours if the community offers them',
    arrivalTimingDetails: 'Timing matters because some communities can explain access policies more easily during office or visitor periods than during prayer times. Arriving in the middle of a ritual period and immediately asking for exceptions places unfair pressure on staff and worshippers.',
    arrivalFlow: 'You may first encounter a gate, office, or outer courtyard rather than the fire temple interior itself. Ask politely at the earliest clear point of contact whether visitors may enter any part of the precinct and where photography, if any, is allowed. If the answer is no, receive that answer calmly and thank the person who told you.',
    whatHappens: ['clear boundaries between public and restricted areas', 'visible respect for the sacred fire even from a distance', 'possible separation between community functions and public information areas', 'ritual purity expectations that shape access', 'quiet movement rather than sightseeing behavior', 'hospitality in designated spaces if the community chooses to offer it'],
    whatHappensNotes: 'The main thing a visitor must understand is that not all sacred places are open in the same way. In Zoroastrian contexts, reverence can mean not entering. Accepting that boundary is not a lesser form of respect. It is the correct form when the community has set it clearly.',
    participationDo: ['ask once, politely, about visitor access', 'follow every boundary exactly as explained', 'keep your voice low in outer precincts', 'show gratitude for any information the community offers'],
    participationAvoid: ['argue for an exception', 'try to peer into restricted rooms', 'take photos where they are not allowed', 'treat the sacred fire as a visual attraction rather than a focus of worship'],
    participationNotes: 'If a community member explains that only Zoroastrians may enter, the respectful response is immediate acceptance. You can still learn from outer spaces, educational materials, or conversation in permitted areas. Respect sometimes means stopping where the community asks you to stop, without resentment.',
    commonMistakes: ['treating access restrictions as a challenge to overcome', 'showing up in tourist mode with cameras ready', 'assuming all temples welcome outsiders equally', 'pressing staff for theological explanations while they are enforcing a boundary', 'speaking loudly in quiet precincts', 'confusing public heritage interest with entitlement to entry'],
    phrases: [
      { phrase: 'Hello', meaning: 'a simple greeting is usually best', whenToUse: 'you first meet staff or a community representative' },
      { phrase: 'May visitors enter this area?', meaning: 'a respectful practical question', whenToUse: 'you need to clarify boundaries before proceeding' },
      { phrase: 'Thank you', meaning: 'the right response after guidance or refusal', whenToUse: 'someone explains access limits or visitor rules' },
    ],
    phraseNotes: 'Plain language works well in a fire temple context because the most important thing is not sounding informed. It is showing that you will obey the answer you receive.',
    relatedLinks: [
      { label: 'Zoroastrianism profile', href: '/religions/zoroastrianism' },
      { label: 'Zoroastrianism reading list', href: '/recommended-reading/zoroastrianism' },
    ],
  },
  {
    title: 'Visiting an Indigenous Ceremony Respectfully',
    tradition: 'Indigenous & Traditional',
    setting: 'community ceremonies and sacred gatherings',
    summaryFocus: 'consent, invitation, photography limits, listening posture, and accepting community-defined boundaries without argument',
    wearRequired: ['clean, modest clothing that does not call attention to you', 'comfortable shoes suitable for outdoor or community terrain', 'weather-appropriate layers', 'simple attire that lets you sit or stand quietly for extended periods'],
    wearAvoid: ['regalia-like clothing that imitates the community', 'festival costumes', 'shirts with slogans that shift focus to you', 'anything that implies you are performing an identity rather than visiting respectfully'],
    wearNotes: 'Indigenous ceremonial settings are the place where many outsiders most need to resist improvisation. Do not dress in ways that imitate sacred or community-specific forms of dress. Your goal is not to look like you belong. Your goal is to behave as a careful guest who understands that invitation, consent, and community authority come first.',
    bringHelpful: ['only items the host has said are appropriate', 'a silent phone kept out of sight', 'water if the host says it is fine', 'a small gift only if the community has explicitly said gifts are customary'],
    bringAvoid: ['cameras unless explicit permission has been granted', 'recording devices', 'gifts chosen from stereotypes', 'expectations that every part of the ceremony is available for outsiders to witness'],
    bringNotes: 'Many Indigenous ceremonies are not public educational experiences. Some are closed entirely. Others are open only through personal invitation. Even when you are invited, do not assume that photography, note-taking, livestreaming, or casual sharing afterward is acceptable. Bring less than you think you need, and let the host define the terms.',
    arrivalWindow: 'whenever the host or community contact instructs, never by personal guesswork alone',
    arrivalTimingDetails: 'Timing is especially important here because ceremony may depend on local protocol, elder guidance, preparation, and invitation. If the host says arrive early, do so. If the host says wait to be met, wait. Independence that looks efficient in other spaces can look disrespectful in a community ceremony.',
    arrivalFlow: 'Follow the exact arrival instructions given by the host. That may mean waiting at a gate, checking in with a designated person, helping with a practical task, or sitting in a place assigned to guests. Do not wander the grounds to orient yourself if no one has told you it is appropriate. Orientation comes from the community, not from personal exploration.',
    whatHappens: ['community-defined welcome or check-in', 'clear instruction about where guests may sit or stand', 'limits on what may be observed, discussed, or shared afterward', 'possible moments of prayer, song, dance, silence, or offerings that are not for outsider imitation', 'a strong role for elders or designated ceremonial leaders', 'boundaries that may remain partly unexplained to outsiders'],
    whatHappensNotes: 'You may not understand every action, and you are not entitled to. In Indigenous ceremonial contexts, respect often means accepting partial understanding. A guest is not there to extract meaning on demand. A guest is there to honor the relationship and the limits the community sets around sacred knowledge and practice.',
    participationDo: ['wait for explicit invitation before joining any action', 'listen more than you speak', 'follow seating and movement instructions exactly', 'ask after the ceremony what may be shared outside the community'],
    participationAvoid: ['photograph or record without explicit permission', 'copy songs, dances, prayers, or gestures because they seem meaningful', 'press for explanations of restricted elements', 'treat the invitation as a chance to collect cultural content'],
    participationNotes: 'If you are unsure whether a gesture is for guests, assume it is not until told otherwise. Gratitude, stillness, and obedience to instruction are stronger signs of respect than visible enthusiasm. In these settings, the visitor who does less usually honors the ceremony more.',
    commonMistakes: ['showing up with a camera', 'asking whether sacred items can be handled for a photo', 'copying dress, words, or ritual movements', 'treating invitation as permission to tell others everything you saw', 'forcing an elder into educator mode during a sacred event', 'mistaking hospitality for unrestricted access'],
    phrases: [
      { phrase: 'Thank you for inviting me', meaning: 'a respectful acknowledgment of hosted access', whenToUse: 'you greet the host or community representative' },
      { phrase: 'Where would you like guests to sit?', meaning: 'a practical question that centers the host’s authority', whenToUse: 'you arrive and are not yet sure where to go' },
      { phrase: 'May I ask about sharing this afterward?', meaning: 'a respectful check on boundaries of retelling', whenToUse: 'the ceremony has ended and the host seems open to questions' },
    ],
    phraseNotes: 'In Indigenous settings, the best vocabulary often centers permission and gratitude. Ask fewer questions, ask better questions, and ask them only when the community has made room for them.',
    relatedLinks: [
      { label: 'Indigenous traditions profile', href: '/religions/indigenous-traditions' },
      { label: 'Compare African Diaspora vs Indigenous Traditions', href: '/compare/african-diaspora-vs-indigenous-traditions' },
    ],
  },
  {
    title: 'Visiting a Pagan Festival Respectfully',
    tradition: 'Paganism & Wicca',
    setting: 'modern Pagan gatherings and ritual festivals',
    summaryFocus: 'consent, privacy, ritual boundaries, photography limits, and how to distinguish public educational spaces from closed sacred circles',
    wearRequired: ['weather-appropriate outdoor clothing', 'modest and practical festival wear', 'layers for day and evening temperature changes', 'footwear suitable for fields, campgrounds, or woodland paths'],
    wearAvoid: ['clothing that mocks or exoticizes Pagan practice', 'assumptions that revealing or costume-like clothing is expected', 'heavy fragrance in close ritual spaces', 'anything that makes it hard to move calmly through mixed public and sacred areas'],
    wearNotes: 'Pagan gatherings range from family-friendly educational festivals to highly private ritual weekends. The right clothing is usually practical, respectful, and adapted to the event’s published norms. Do not assume that because some attendees dress creatively, you should arrive in theatrical clothing you would not otherwise wear. Outsiders should not perform Pagan identity as a costume.',
    bringHelpful: ['a silent phone', 'water and practical outdoor basics if the event permits them', 'a flashlight for nighttime navigation if the event guide recommends one', 'cash or card for vendors only if you are attending the public portions of the event'],
    bringAvoid: ['cameras for close-up ritual photos without permission', 'recording devices in sacred circles', 'food or drinks carried into a circle unless explicitly allowed', 'expectations that every workshop or ritual is open to non-members'],
    bringNotes: 'Many Pagan festivals mix public education with private ritual. That means what is fine at a vendor area or lecture tent may be unacceptable at a circle, shrine, or evening rite. Keep gear minimal and check the event policy before assuming you can film, photograph, or enter with a drink. Consent culture is usually central.',
    arrivalWindow: 'according to the event check-in instructions, and early enough to read the site rules before the first activity you attend',
    arrivalTimingDetails: 'Festivals often require registration, wristbands, parking coordination, or campsite orientation. If you arrive right as a workshop or ritual begins, you may miss the rules that explain what is public, what is closed, and what forms of photography or participation are forbidden.',
    arrivalFlow: 'Most events have a registration point, schedule board, and map. Start there. Learn which spaces are open teaching areas, which are private ritual circles, and whether there are color-coded badges or signs indicating who may be photographed or approached for conversation. Do not wander into a circle because it looks visually interesting.',
    whatHappens: ['registration or check-in', 'public workshops, talks, or vendor areas', 'scheduled rituals that may be open, invitation-only, or closed', 'clear consent norms around touch, photos, and participation', 'shared meals or camp-style logistics at some events', 'quiet transitions around ritual spaces that are not part of the entertainment schedule'],
    whatHappensNotes: 'The biggest etiquette challenge at Pagan festivals is that the boundary between public and sacred can change from one field or hour to the next. A drumming circle might be open in the afternoon and private at night. A ritual may welcome observers but not photographers. The visitor must keep reading the room and the posted rules, not rely on one assumption for the whole event.',
    participationDo: ['check the event policy before entering any ritual space', 'ask whether a circle is open, closed, or invite-only', 'respect name, pronoun, and privacy preferences', 'leave immediately if staff or ritual leaders say a space is not for observers'],
    participationAvoid: ['photograph altars, ritual tools, or participants without permission', 'treat an open festival as permission to attend every rite', 'touch people, costumes, or tools without consent', 'reduce serious practice to aesthetic curiosity'],
    participationNotes: 'At Pagan festivals, consent is not just social niceness. It is a core ritual boundary. If you are unsure whether you belong in a space, ask. If the answer is no, accept it gracefully. If a ritual is open, stay attentive to its stated limits, because openness rarely means anything goes.',
    commonMistakes: ['treating every visible ritual as public theater', 'taking photos because the setting looks dramatic', 'assuming all attendees want to explain their path to strangers', 'confusing a public festival ticket with full ceremonial access', 'entering circles without asking', 'touching altars, drums, or ritual objects because they seem communal'],
    phrases: [
      { phrase: 'Is this circle open to guests?', meaning: 'a respectful question about ritual access', whenToUse: 'you approach a space and are not sure whether visitors are allowed' },
      { phrase: 'May I take photos here?', meaning: 'a direct consent question', whenToUse: 'you are in a public area and still need permission before photographing people or ritual spaces' },
      { phrase: 'Thank you for clarifying', meaning: 'grateful acceptance of a boundary', whenToUse: 'staff or practitioners explain what is or is not open' },
    ],
    phraseNotes: 'At Pagan events, explicit questions about access and consent are signs of maturity, not ignorance. Ask clearly, accept the answer, and remember that privacy can be a spiritual need as well as a social one.',
    relatedLinks: [
      { label: 'Paganism & Wicca profile', href: '/religions/paganism-wicca' },
      { label: 'Paganism & Wicca reading list', href: '/recommended-reading/paganism-wicca' },
    ],
  },
];
