import type { EtiquetteGuideSeed } from '@/lib/resource-details/etiquette-guide-types';

export const ETIQUETTE_GUIDE_SEEDS_C: EtiquetteGuideSeed[] = [
  {
    title: 'Visiting a Zen Center Respectfully',
    tradition: 'Buddhism',
    setting: 'Zen temples and meditation centers',
    summaryFocus: 'zazen silence, posture rules, entry bows, and careful attention to teacher instructions',
    wearRequired: ['plain, modest clothing', 'dark or neutral colors in stricter centers', 'socks you can walk in quietly', 'loose clothes that allow seated meditation'],
    wearAvoid: ['perfume', 'jewelry that rattles', 'tight jeans that make floor sitting difficult', 'shirts with bold graphics'],
    wearNotes: 'Zen centers often value simplicity, so understated clothing is usually better than trying to look spiritual. If the center provides cushions, benches, or robes, use them as instructed rather than arranging the room to your taste. Clothing should help you disappear into the rhythm of practice rather than stand out.',
    bringHelpful: ['a silent phone left outside the zendo if possible', 'a water bottle kept outside the meditation room', 'a notebook for use after instruction periods', 'layers if the room is cool'],
    bringAvoid: ['food in the zendo', 'large bags', 'camera equipment', 'anything that will make noise when you bow or sit'],
    bringNotes: 'Many Zen centers have a clear boundary between the public entry area and the zendo, the meditation hall. Carry as little as possible across that boundary. If you are given a cushion and mat, use the exact spot assigned to you and do not step on another person’s zabuton or meditation seat.',
    arrivalWindow: '20 to 30 minutes before zazen or orientation begins',
    arrivalTimingDetails: 'Zen schedules can be exact. Bells, bows, and entry lines may happen on the minute, and late entry can interrupt a room that has already gone completely silent. Arriving early gives you time to learn whether the center expects bows at the doorway, assigned seating, or a short orientation for first-time visitors.',
    arrivalFlow: 'You may be asked to wait quietly in a lobby until a leader invites the group into the meditation hall. In many centers, people bow at the threshold, move clockwise around the room, place shoes in a specific area, and sit facing a wall or toward the center depending on the school. Follow the staff, not your instincts, because the room choreography matters.',
    whatHappens: ['a bell or clapper signaling entry', 'formal bows on entering or taking a seat in many centers', 'periods of seated meditation, called zazen', 'walking meditation between sits in some communities', 'a Dharma talk or brief instructions', 'closing bows and silent departure from the hall'],
    whatHappensNotes: 'The striking feature of a Zen center is disciplined silence. Even small noises can feel large in a room where people are concentrating on posture and breath. You may also see a teacher or monitor adjusting posture etiquette, signaling transitions, or walking the perimeter during meditation. None of this is casual. It is part of the practice environment.',
    participationDo: ['follow posture instructions exactly as given', 'bow when the group bows if you are comfortable doing so', 'keep your eyes lowered and movements slow', 'ask questions during designated instruction time, not during silent sitting'],
    participationAvoid: ['cross the zendo once sitting has begun', 'stretch noisily in the room', 'touch another person’s cushion', 'decide on your own to leave the hall mid-period unless there is a real need'],
    participationNotes: 'If you cannot sit cross-legged, tell the host before practice starts. Most centers can provide a bench or chair. This is far better than enduring pain until you move suddenly during silent sitting. Zen etiquette values honesty and discipline more than heroic performance.',
    commonMistakes: ['arriving late and entering after the room is silent', 'whispering because the space looks informal', 'slouching on a cushion as if it were casual lounge seating', 'treating bows as theatrical rather than functional', 'stepping over meditation cushions', 'asking questions in the middle of a bell-marked silent period'],
    phrases: [
      { phrase: 'Zazen', meaning: 'seated meditation in the Zen tradition', whenToUse: 'you are clarifying what part of the schedule is about to begin' },
      { phrase: 'Dokusan', meaning: 'private interview with a teacher in some Zen settings', whenToUse: 'the center offers it and you are told visitors may request it' },
      { phrase: 'Gassho', meaning: 'palms joined in a respectful gesture', whenToUse: 'a teacher explains that this is the gesture used for bowing or greeting' },
    ],
    phraseNotes: 'Zen language is usually introduced by the center itself. Use the words only after orientation has made them clear. In the first visit, careful posture and silence communicate respect better than vocabulary.',
    relatedLinks: [
      { label: 'Buddhism profile', href: '/religions/buddhism' },
      { label: 'Glossary: Nirvana', href: '/glossary/nirvana' },
    ],
  },
  {
    title: 'Visiting a Gurdwara Respectfully',
    tradition: 'Sikhism',
    setting: 'gurdwaras and Sikh prayer halls',
    summaryFocus: 'head coverings, shoe removal, reverence for the Guru Granth Sahib, and langar etiquette',
    wearRequired: ['modest clothing that covers shoulders and knees', 'a head covering for everyone, often a scarf or bandana', 'clean socks for the no-shoes area', 'comfortable clothing for sitting on the floor'],
    wearAvoid: ['shorts', 'bare heads', 'revealing tops', 'clothing with tobacco or alcohol branding'],
    wearNotes: 'The head covering is not optional in a gurdwara. If you do not bring one, many gurdwaras provide scarves near the entrance. Tie it securely before entering the prayer hall. Modest clothing matters because guests usually sit on the floor and move through spaces that are treated with visible reverence.',
    bringHelpful: ['a scarf or bandana for your head', 'a silent phone', 'a small donation if you want to support langar or the community', 'a bag small enough to store neatly'],
    bringAvoid: ['tobacco, alcohol, or intoxicants on your person', 'food brought casually into the prayer hall', 'large backpacks', 'shoes carried into carpeted worship areas'],
    bringNotes: 'Sikh spaces are very sensitive to cleanliness and reverence around the Guru Granth Sahib, the scripture treated as the living Guru. Wash your hands if facilities are provided. If you carry belongings, keep them tucked away and never place them on a platform, cushion, or railing near the scripture.',
    arrivalWindow: '15 to 20 minutes before a service, and earlier if you want to understand the entry sequence calmly',
    arrivalTimingDetails: 'That time helps you cover your head, remove shoes, wash hands, and learn where to sit before kirtan or scripture reading is underway. Walking in while people are already bowing or singing can be more awkward than first-time visitors expect.',
    arrivalFlow: 'Most visitors remove shoes, wash hands, cover the head, and then enter the diwan hall, the main prayer hall. Many people approach the Guru Granth Sahib, bow, and place an offering before taking a seat. You are not required to offer money, but you should pause respectfully and avoid crossing directly between worshippers and the scripture platform.',
    whatHappens: ['kirtan, devotional singing', 'readings from the Guru Granth Sahib', 'bowing on approach to the scripture', 'separate seating areas for men and women in some gurdwaras', 'distribution of karah prasad in many services', 'langar, the communal meal, after worship in many communities'],
    whatHappensNotes: 'The gurdwara combines reverence and hospitality. Worship in the hall is quiet, ordered, and focused on the Guru Granth Sahib. Langar afterward is active, communal, and practical, with people eating together on equal terms. Visitors should treat both spaces respectfully. One is not more important than the other. Both express Sikh principles.',
    participationDo: ['cover your head before entering', 'sit on the floor if you are able, often cross-legged', 'accept karah prasad with both hands or the right hand supported by the left', 'join langar if invited and eat respectfully'],
    participationAvoid: ['turn your feet toward the Guru Granth Sahib', 'stand above seated worshippers for a better view', 'decline head covering rules because you are a visitor', 'treat langar like free food without noticing the seva, or service, behind it'],
    participationNotes: 'If you cannot sit on the floor, ask quietly whether chairs are available. Many gurdwaras accommodate this. During langar, follow the room. Sit where directed, accept food gratefully, and avoid waste. The meal is a sacred practice of equality, not an afterthought to the service.',
    commonMistakes: ['forgetting to cover the head', 'bringing tobacco products onto the premises', 'photographing the scripture platform up close without permission', 'handling prasad casually', 'skipping hand washing where it is expected', 'treating the langar hall like a cafeteria rather than a devotional act of service'],
    phrases: [
      { phrase: 'Sat Sri Akal', meaning: 'a common Sikh greeting, often understood as truth is eternal', whenToUse: 'you greet hosts or attendees in an appropriate Sikh setting' },
      { phrase: 'Langar', meaning: 'the communal kitchen and shared meal', whenToUse: 'you are being shown where the meal takes place' },
      { phrase: 'Seva', meaning: 'selfless service', whenToUse: 'you are learning why volunteers are cooking, cleaning, or serving' },
    ],
    phraseNotes: 'A gurdwara is often very welcoming to guests, but welcome does not cancel discipline. Learn the words slowly, and show respect first through head covering, cleanliness, and the way you handle prasad and langar.',
    relatedLinks: [
      { label: 'Sikhism profile', href: '/religions/sikhism' },
      { label: 'Sikhism reading list', href: '/recommended-reading/sikhism' },
    ],
  },
  {
    title: 'Visiting a Shinto Shrine Respectfully',
    tradition: 'Shinto',
    setting: 'shrines and shrine precincts',
    summaryFocus: 'torii gate etiquette, purification, offering customs, and how to move through an active shrine respectfully',
    wearRequired: ['clean everyday clothing', 'modest tops and bottoms', 'comfortable shoes for gravel paths and stairs', 'weather-appropriate layers'],
    wearAvoid: ['partywear', 'very revealing clothes', 'costumes that treat the shrine like a theme park', 'shoes that make it hard to move calmly on stone and gravel'],
    wearNotes: 'Shinto shrines often feel outdoorsy and visually open, but they are not casual parks. Clean, practical clothing is usually enough, yet your posture and pacing matter as much as what you wear. Dress so that you can pause, bow, and walk without rushing. On festival days, crowds may be large, so neat and unobtrusive clothing helps keep the atmosphere respectful.',
    bringHelpful: ['a silent phone', 'small coins for an offering box if you want to make one', 'water kept sealed and consumed outside the main prayer area', 'an umbrella that can be folded and stored neatly'],
    bringAvoid: ['food near the main hall', 'loud music from earbuds or speakers', 'tripods without permission', 'objects placed on railings, lanterns, or offering areas'],
    bringNotes: 'Many shrine visits are short and simple, so you do not need much. If you buy an ema, omamori, or fortune slip, handle it carefully and follow the instructions about where to hang or tie it. Do not improvise your own place to leave ritual items.',
    arrivalWindow: '10 to 15 minutes before a festival procession, and anytime with a slow pace during ordinary visiting hours',
    arrivalTimingDetails: 'Shrines can be visited more flexibly than many indoor worship spaces, but timing still matters if a ceremony is underway. Arriving before a procession, formal prayer, or purification event begins lets you stand aside rather than being redirected in the middle of it.',
    arrivalFlow: 'Visitors usually pass through a torii gate, walk along the approach path, and pause at the temizuya, the water pavilion, to rinse hands and sometimes the mouth according to local custom. On the main approach, many people avoid walking down the exact center, which is often treated as the path reserved for the kami, the sacred presence. Watch where regular visitors position themselves.',
    whatHappens: ['passing through one or more torii gates', 'purification at the water pavilion in many shrines', 'approach to the main hall', 'placing a coin in the offering box', 'bowing, clapping, and bowing again in a common prayer pattern at some shrines', 'buying charms, plaques, or festival items in busier complexes'],
    whatHappensNotes: 'Shrine etiquette is often quiet and brief, but very patterned. Local custom matters. Some shrines use a two bows, two claps, one bow sequence, while others vary. The key is not to perform from memory if you are unsure. Observe, then follow carefully, especially around the main hall where worshippers may approach in a short line.',
    participationDo: ['walk calmly and avoid the center of the main approach when that is the local custom', 'purify at the water pavilion if you know the sequence or can watch others first', 'make a small offering if you wish', 'step aside after prayer so others can approach'],
    participationAvoid: ['lean on shrine structures', 'ring bells or clap for fun', 'treat torii gates as playground or photo props', 'block worshippers while setting up photos'],
    participationNotes: 'If you are uncertain about the bow-clap pattern, a simple bow and respectful pause is better than a flashy incorrect performance. Shrines often host both tourists and worshippers, so your job is to avoid turning the worship area into your personal photography zone.',
    commonMistakes: ['walking straight down the middle of the main approach where local custom discourages it', 'skipping purification and then crowding the prayer line', 'posing dramatically under the torii during active worship hours', 'touching ritual objects without permission', 'ringing bells repeatedly', 'buying charms and then treating them like novelty souvenirs'],
    phrases: [
      { phrase: 'Konnichiwa', meaning: 'hello or good day', whenToUse: 'you greet staff or volunteers in a general Japanese setting' },
      { phrase: 'Omamori', meaning: 'protective charm', whenToUse: 'you are asking about an item sold at the shrine office' },
      { phrase: 'Temizuya', meaning: 'the purification water pavilion', whenToUse: 'you want to identify where purification happens' },
    ],
    phraseNotes: 'You do not need ritual Japanese to visit respectfully. Moving calmly, observing the approach path, and not crowding the prayer line matter far more than specialized language.',
    relatedLinks: [
      { label: 'Shinto profile', href: '/religions/shinto' },
      { label: 'Shinto reading list', href: '/recommended-reading/shinto' },
    ],
  },
  {
    title: 'Visiting a Jain Temple Respectfully',
    tradition: 'Jainism',
    setting: 'derasars and Jain temple complexes',
    summaryFocus: 'cleanliness, nonviolence, quiet bodily conduct, and specific care around food, leather, and shrine boundaries',
    wearRequired: ['very clean, modest clothing', 'covered shoulders and knees', 'easy-to-remove shoes', 'simple garments without leather accessories if possible'],
    wearAvoid: ['shorts', 'revealing tops', 'leather belts or bags where the temple discourages them', 'food-stained or sloppy clothing'],
    wearNotes: 'Jain temple etiquette is strongly shaped by ideas of purity, cleanliness, and non-harm. A visitor should look orderly and restrained. Some temples discourage leather items out of respect for ahimsa, nonviolence. Even where this is not strictly enforced, minimizing animal-derived accessories is a thoughtful choice.',
    bringHelpful: ['a silent phone', 'clean socks for the no-shoes area', 'minimal belongings', 'a handkerchief or tissues kept discreetly'],
    bringAvoid: ['food in sacred areas', 'flowers or offerings unless the temple explicitly allows them', 'leather-heavy accessories', 'anything messy, scented, or noisy'],
    bringNotes: 'Because Jain spaces often emphasize cleanliness, you should not bring snacks, open drinks, or casual clutter into the temple. If a temple provides a washing area, use it. Keep belongings off the floor when possible and never place personal items on platforms, railings, or around sacred images.',
    arrivalWindow: '15 minutes before ritual periods, or at a calm hour when you can learn the flow without crowds',
    arrivalTimingDetails: 'Early arrival helps because some Jain temples have specific routes, upper and lower levels, or times when the shrine is being cleaned or prepared. If you arrive just as a rite begins, you may not know where guests should stand and you may end up blocking a very quiet ritual movement.',
    arrivalFlow: 'Most visitors remove shoes before entry and may wash hands before approaching the inner area. Movement is often slow and quiet. Watch where regular worshippers stop, bow, or circle. If there are posted purity rules, such as restrictions related to food, photography, or access to inner spaces, follow them exactly rather than looking for exceptions.',
    whatHappens: ['shoe removal and sometimes hand washing before the inner space', 'quiet movement toward shrine images of the Tirthankaras', 'bowing or folded hands before the images', 'offerings or ritual actions in some communities', 'periods of silence or recitation', 'careful circulation through clean temple corridors and shrine rooms'],
    whatHappensNotes: 'Jain temples often feel exceptionally controlled and serene. This is not accidental. The environment itself expresses nonviolence, restraint, and purity. Visitors should not assume that because the room is quiet it is informal. In many ways the opposite is true. Quiet means greater sensitivity to movement, smell, and bodily carelessness.',
    participationDo: ['remove shoes promptly and neatly', 'move slowly and quietly', 'ask before taking any photos', 'honor posted purity rules without debate'],
    participationAvoid: ['bring food into sacred areas', 'touch images or ritual objects without permission', 'track dirt into the inner temple', 'treat the space like a sightseeing monument'],
    participationNotes: 'If you are invited to perform a small gesture such as folded hands or a respectful bow, you may do so simply. Do not improvise elaborate ritual actions. In Jain settings, care, cleanliness, and non-disturbance matter more than outward display.',
    commonMistakes: ['arriving with snacks or drinks', 'ignoring no-leather guidance where it is present', 'speaking in a normal public voice in a very quiet shrine', 'assuming photography is acceptable because the space is beautiful', 'moving too quickly through narrow shrine areas', 'forgetting that nonviolence also shapes how gently you move through the environment'],
    phrases: [
      { phrase: 'Jai Jinendra', meaning: 'a respectful Jain greeting', whenToUse: 'hosts or visitors are already using it in the temple context' },
      { phrase: 'Ahimsa', meaning: 'nonviolence', whenToUse: 'you want to understand why so many temple rules emphasize restraint and care' },
      { phrase: 'Derasar', meaning: 'Jain temple', whenToUse: 'you are confirming that you are in the correct building or asking about the main worship area' },
    ],
    phraseNotes: 'In Jain settings, the best phrase is often a soft voice and careful motion. If you do use Jain terms, use them with humility. Clean conduct is the primary language of respect here.',
    relatedLinks: [
      { label: 'Jainism profile', href: '/religions/jainism' },
      { label: 'Compare Hinduism vs Jainism', href: '/compare/hinduism-vs-jainism' },
    ],
  },
];
