import type { EtiquetteGuideSeed } from '@/lib/resource-details/etiquette-guide-types';

export const ETIQUETTE_GUIDE_SEEDS_B: EtiquetteGuideSeed[] = [
  {
    title: 'Visiting Friday Prayer Respectfully',
    tradition: 'Islam',
    setting: "Jumu'ah congregational prayer",
    summaryFocus: 'Friday sermon timing, mosque crowd flow, silence during the khutbah, and how visitors should navigate the busiest weekly prayer',
    wearRequired: ['the same modest standards expected for any mosque, including covered shoulders, chest, and knees', 'loose clothing', 'a headscarf for women where expected', 'easy-to-remove shoes with clean socks'],
    wearAvoid: ['rushed after-work clothing that leaves the knees or shoulders bare', 'tight sportswear', 'strong perfume', 'anything that makes quick shoe removal awkward'],
    wearNotes: 'Friday prayer is busier and more structured than ordinary daily prayer, so dress should be sorted out before you arrive. This is not the day to assume that a lenient dress code will slide because the building is crowded. Crowded buildings usually mean volunteers have less time to solve preventable issues at the door.',
    bringHelpful: ['a silent phone', 'a small donation if the mosque collects on Fridays', 'minimal belongings', 'a plain scarf if needed'],
    bringAvoid: ['food, coffee, or water in the prayer hall', 'large bags', 'camera gear', 'anything that will slow you down in the entrance queue'],
    bringNotes: 'Jumuah often creates lines at the shoe racks, restrooms, and entrances. The visitor who moves best is the one carrying the least. If you bring a bag, keep it compact and out of the walkways because late arrivals continue entering until the sermon begins.',
    arrivalWindow: '25 to 40 minutes before the khutbah begins',
    arrivalTimingDetails: 'That earlier window matters because the khutbah is not background commentary. Worshippers are expected to listen attentively once it begins. Arriving after the sermon starts forces others to move, turns heads, and may place you in the worst possible position to understand what is happening.',
    arrivalFlow: 'Expect volunteers directing traffic, fuller parking lots, and a stronger separation between entrance, shoe area, and prayer rows than on weekday visits. A host may point you to an overflow room, balcony, or rear section. Accept that direction immediately instead of negotiating for a better view.',
    whatHappens: ['worshippers gathering and settling before noon', 'a formal sermon, called the khutbah, delivered before the congregational prayer', 'near-complete silence from the congregation while the sermon is underway', 'rows forming for the prayer after the sermon', 'a short congregational salah following the khutbah', 'greetings, announcements, and quick conversations after the prayer ends'],
    whatHappensNotes: 'The key difference from a casual visit is the sermon discipline. Many Muslims understand speaking during the khutbah as a serious breach of etiquette. Even a whispered side comment or an unnecessary phone glance can look disrespectful because the entire room is oriented toward listening.',
    participationDo: ['take your place before the khutbah begins', 'sit quietly and still during the sermon', 'follow a host to overflow seating if the main hall is full', 'wait until the prayer ends before asking questions'],
    participationAvoid: ['arrive at the moment the sermon starts', 'talk once the khutbah has begun', 'step across filled rows to find a more central spot', 'film the congregation during the sermon or prayer'],
    participationNotes: 'If you are only observing, that is fine. Sit where instructed, keep your attention forward, and remain still through the sermon and prayer. If you are uncertain whether a movement in the row behind you signals the prayer is starting, wait half a beat and follow the host or the last row, not the front row, so you do not rush into the wrong place.',
    commonMistakes: ['treating the khutbah like a lecture you can chat through', 'arriving so late that others must compress their rows', 'trying to stand in the back doorway to watch', 'checking messages during the sermon', 'blocking exits while putting shoes back on', 'asking long questions before worshippers have finished greeting one another after prayer'],
    phrases: [
      { phrase: 'Jumuah mubarak', meaning: 'blessed Friday', whenToUse: 'you greet people after the prayer, not during the sermon' },
      { phrase: 'As-salamu alaykum', meaning: 'peace be upon you', whenToUse: 'you greet a host or volunteer briefly before or after prayer' },
      { phrase: 'Khutbah', meaning: 'Friday sermon', whenToUse: 'you want to understand why silence matters before the prayer itself' },
    ],
    phraseNotes: 'Friday prayer is less about saying the right phrase and more about honoring the room with timing and silence. Learn the word khutbah, arrive early, and let your restraint do most of the respectful work.',
    relatedLinks: [
      { label: 'Islam profile', href: '/religions/islam' },
      { label: 'Glossary: Halal', href: '/glossary/halal' },
    ],
  },
  {
    title: 'Visiting a Synagogue Respectfully',
    tradition: 'Judaism',
    setting: 'synagogues and Jewish congregations',
    summaryFocus: 'security procedures, modest dress, prayer-book use, Torah respect, and how visitors should handle varied Jewish customs',
    wearRequired: ['modest clothing that covers chest and knees', 'quiet shoes', 'a jacket or sweater for formal congregations', 'a kippah for men if the congregation expects one, often provided at the entrance'],
    wearAvoid: ['revealing clothing', 'slogans or political graphics', 'hats that ignore the local head-covering custom', 'anything that will draw attention during prayer'],
    wearNotes: 'Dress varies among Reform, Conservative, Orthodox, and independent communities, but modest, neat clothing is the safest standard everywhere. Men should be ready to cover their heads if the synagogue asks. Women visiting traditional congregations should choose clothing with higher necklines, sleeves, and skirts or dresses below the knee, or well-tailored trousers if the community accepts them.',
    bringHelpful: ['a photo ID if the synagogue has security protocols', 'a silent phone that stays away during worship', 'reading glasses', 'a respectful willingness to follow instructions from security staff'],
    bringAvoid: ['large backpacks unless necessary', 'food in the sanctuary', 'unannounced gifts', 'cameras unless you have explicit prior permission'],
    bringNotes: 'Security is a normal part of synagogue life in many places. Do not take it personally if staff ask your name, check your ID, or confirm that you contacted the synagogue beforehand. That process is there to protect the congregation. Keep your answers calm and simple, and do not joke about security procedures.',
    arrivalWindow: '15 to 20 minutes before the service, or earlier if you are a first-time guest who needs to clear security',
    arrivalTimingDetails: 'That extra time matters because security check-in can take a few minutes, and visitors often need help finding the right prayer book or the correct seating section. Arriving a minute before worship starts can mean beginning the visit with anxiety instead of attention.',
    arrivalFlow: 'After security or a front-desk check, a greeter may hand you a siddur, the prayer book, and possibly a kippah. Some synagogues have ushers who help visitors find seats. Others expect you to settle quietly on your own. If the congregation has a separate social hall, do not assume the service begins there. Follow the flow toward the sanctuary or prayer room.',
    whatHappens: ['Hebrew and English prayers from a siddur', 'congregational standing and sitting at several points', 'scripture readings or a sermon', 'opening of the ark in many services', 'Torah reading on services that include it', 'community announcements, kiddush, or a social hour afterward in many congregations'],
    whatHappensNotes: 'Jewish services vary by movement, but the Torah scroll is always treated with visible reverence. People may kiss the edge of a prayer shawl or book and touch it to the Torah as it passes. Visitors are not expected to imitate this automatically. When the ark is opened, many congregations stand. Following that cue is usually appropriate even if you do not know the Hebrew prayers.',
    participationDo: ['stand when the congregation stands, especially when the ark is open', 'use the siddur even if you can only follow part of it', 'ask quietly where visitors should sit if the room layout is not obvious', 'stay for kiddush or coffee afterward if invited'],
    participationAvoid: ['touch the Torah scroll without invitation', 'photograph worshippers or children', 'assume every synagogue permits the same behavior on the Sabbath', 'treat security procedures as optional'],
    participationNotes: 'Visitors do not need to recite every prayer to be respectful. Following the room, staying attentive, and handling books carefully are the main things. If someone offers you a kippah or prayer shawl, ask whether guests usually wear it rather than refusing abruptly or putting it on carelessly.',
    commonMistakes: ['showing up without checking the congregation policy for visitors', 'joking with security staff', 'using a phone during a service in a community that avoids technology on sacred time', 'reaching toward the Torah out of curiosity', 'assuming all synagogues are alike', 'starting theological debates during the social hour'],
    phrases: [
      { phrase: 'Shalom', meaning: 'peace, hello, or goodbye depending on context', whenToUse: 'you greet hosts or attendees simply and warmly' },
      { phrase: 'Todah', meaning: 'thank you', whenToUse: 'someone helps you find a seat or prayer book' },
      { phrase: 'Siddur', meaning: 'prayer book', whenToUse: 'you need to ask politely for the correct book' },
    ],
    phraseNotes: 'If you are visiting on Friday evening or Saturday, you may also hear Shabbat shalom, which is an appropriate greeting for the Sabbath. Use it after you have heard the community use it, and keep your tone warm and simple.',
    relatedLinks: [
      { label: 'Judaism profile', href: '/religions/judaism' },
      { label: 'Judaism reading list', href: '/recommended-reading/judaism' },
    ],
  },
  {
    title: 'Visiting a Shabbat Service Respectfully',
    tradition: 'Judaism',
    setting: 'Friday night and Saturday worship',
    summaryFocus: 'Sabbath timing, technology limits, prayer-book etiquette, and how to honor the rhythm of Shabbat as a guest',
    wearRequired: ['modest, neat clothing suitable for a sacred day', 'a jacket, dress, or collared shirt in more formal congregations', 'a kippah for men if the community expects it', 'comfortable shoes for standing and walking without noise'],
    wearAvoid: ['workout clothing', 'flashy party wear', 'shirts with slogans', 'anything that treats the Sabbath like a casual drop-in event'],
    wearNotes: 'Shabbat is sacred time, not only a weekly meeting. Your clothing should communicate that you understand this. Friday night services tend to be dressier than weekday gatherings, and Saturday morning services in traditional communities can also include a shared meal, kiddush, or longer social time afterward.',
    bringHelpful: ['a photo ID for security if requested', 'a silent phone that stays unused during the service', 'reading glasses', 'a printed note with the synagogue address and contact information if you are visiting a community that avoids phone use on Shabbat'],
    bringAvoid: ['food in the sanctuary', 'pens for note-taking during worship in communities that avoid writing on Shabbat', 'camera equipment', 'expectations that technology will be casually used around you'],
    bringNotes: 'Some Jewish communities, especially Orthodox ones, avoid using phones, cameras, writing, and other forms of work on Shabbat. That means the respectful visitor plans ahead. Put your phone away before you enter, know where you are going, and do not ask hosts to solve preventable logistics with their phones after the service begins.',
    arrivalWindow: '15 to 20 minutes before Friday night services, and 20 to 30 minutes before Saturday morning worship',
    arrivalTimingDetails: 'Friday night arrival can be especially important because communities often shift quickly from conversation to candles, songs, and prayer. Saturday morning services may include a Torah reading, which means that late arrival can be more disruptive because the room is already in a steady rhythm of standing, chanting, and movement around the Torah.',
    arrivalFlow: 'Expect a security check in many communities. Once inside, you may be handed a siddur and shown where guests usually sit. If it is Friday evening, the mood may feel warm and welcoming but still measured. Let the room settle before greeting people across rows or turning the aisle into a conversation space.',
    whatHappens: ['welcoming Sabbath songs on Friday night in many communities', 'set prayers from the siddur', 'standing when the ark is opened or when the Torah is carried', 'a Torah reading on Saturday morning in many congregations', 'a sermon or teaching', 'a kiddush or shared meal after worship in many communities'],
    whatHappensNotes: 'Shabbat services often combine joy and restraint. There may be more singing than on a weekday, but there is also a strong expectation that sacred time is not interrupted by ordinary errands, casual device use, or noisy movement. Follow the room carefully, especially when the Torah is brought out or when congregants stop speaking all at once for a prayer.',
    participationDo: ['stand when the congregation stands', 'follow the siddur even if you only catch some of the prayers', 'join the post-service kiddush if invited', 'wish people Shabbat shalom after hearing the community use it'],
    participationAvoid: ['check your phone during worship', 'write notes in a community that avoids writing on Shabbat', 'ask people to pose for photos', 'assume that a friendly atmosphere means casual Sabbath rules do not matter'],
    participationNotes: 'The visitor who handles Shabbat best is the visitor who slows down. Watch first, then act. If a host invites you to a meal after the service, that is often where questions belong. During the service itself, restraint is the better form of participation.',
    commonMistakes: ['bringing technology habits directly into a Sabbath setting', 'asking for exceptions because you are only visiting', 'treating Friday night like a concert', 'moving in and out of the room during prayers', 'touching the Torah or ritual objects without guidance', 'using the social hour to interrogate members about politics or identity'],
    phrases: [
      { phrase: 'Shabbat shalom', meaning: 'peaceful Sabbath', whenToUse: 'you greet people before or after the service' },
      { phrase: 'Todah', meaning: 'thank you', whenToUse: 'someone helps you find the right page or seat' },
      { phrase: 'Kiddush', meaning: 'the blessing over wine, and often the social gathering that follows', whenToUse: 'someone invites you to stay after the service' },
    ],
    phraseNotes: 'Shabbat language is not complicated, but timing matters. A quiet Shabbat shalom at the doorway or social hall is better than breaking a prayerful moment to try out a phrase you have just learned.',
    relatedLinks: [
      { label: 'Judaism profile', href: '/religions/judaism' },
      { label: 'Compare Islam vs Judaism', href: '/compare/islam-vs-judaism' },
    ],
  },
  {
    title: 'Visiting a Hindu Temple Respectfully',
    tradition: 'Hinduism',
    setting: 'mandirs and temple complexes',
    summaryFocus: 'shoe removal, modest dress, darshan etiquette, offerings, and movement through shrine space',
    wearRequired: ['modest clothing that covers shoulders and knees', 'easy-to-remove shoes or sandals', 'clean socks if you prefer not to walk barefoot', 'clothing suitable for sitting, standing, and possibly floor seating'],
    wearAvoid: ['short shorts', 'tank tops', 'leather items if the temple discourages them', 'tight clothing that makes bowing or floor sitting awkward'],
    wearNotes: 'Many Hindu temples expect clothing that feels clean, modest, and non-disruptive. Traditional clothing is welcome if worn respectfully, but it is not required. Because shoes come off before entering the shrine area, you should also think about foot comfort, clean socks, and whether your clothing allows you to move easily when the queue for darshan slows or changes shape.',
    bringHelpful: ['a small cash offering if you want to place one in the donation box', 'flowers or fruit only if the temple explicitly accepts them', 'a silent phone', 'a scarf or shawl for additional coverage'],
    bringAvoid: ['meat products', 'open drinks', 'random objects placed on shrines without permission', 'large bags that bump into railings or other worshippers'],
    bringNotes: 'Temples differ in what offerings they accept. Some welcome fruit, flowers, coconuts, or sweets bought from an approved stall. Others prefer that visitors make only monetary offerings. Ask before placing anything near a deity image. The respectful visitor never treats the shrine as a shelf for personal items or souvenirs.',
    arrivalWindow: '15 to 20 minutes before aarti, puja, or a major festival period, and 10 minutes before a quieter visit',
    arrivalTimingDetails: 'Arriving early matters because temple traffic can change quickly when aarti begins, when bells ring, or when a priest starts distributing prasad. A few extra minutes help you learn the shoe area, queue pattern, and whether a particular shrine is open or restricted at that hour.',
    arrivalFlow: 'Most visitors remove shoes outside the main shrine area, wash hands if facilities are provided, and then move toward the deity images in a clockwise or clearly marked pattern. Some temples have multiple shrines, so do not assume the first doorway leads to the main sanctum. Watch the queue and note where worshippers pause, bow, or step aside after darshan.',
    whatHappens: ['shoe removal before the sacred area', 'darshan, the act of respectfully seeing and being seen by the deity', 'bells, chanting, or music during aarti or puja', 'offerings presented to priests or placed in designated areas', 'distribution of prasad, blessed food, in many temples', 'movement between several shrines in larger temple complexes'],
    whatHappensNotes: 'Temple worship can be more fluid than a seated service. People may enter and leave at different times, but the shrine itself remains the center. Priests may wave lamps, ring bells, offer incense, and recite prayers on behalf of the community. Visitors should stay aware of who is queuing, where the priest is moving, and whether a rail or threshold marks a limit on access.',
    participationDo: ['remove shoes neatly and place them in the correct area', 'join the darshan queue patiently', 'accept prasad with the right hand or with both hands if it is offered', 'step aside after your turn so others can approach the deity'],
    participationAvoid: ['touch deity images or shrine objects unless invited', 'enter the innermost sanctum without permission', 'point your feet directly at sacred images if seated on the floor', 'treat prasad like an ordinary snack and discard it carelessly'],
    participationNotes: 'If you receive tilak or another mark on the forehead, accept it only if you are comfortable, and do so respectfully. If you decline prasad or a ritual gesture, decline gently with a slight bow or a quiet thank you rather than with abrupt refusal. The point is to honor the sacred exchange even if you are not participating fully.',
    commonMistakes: ['walking into the shrine area with shoes on', 'cutting the darshan queue', 'placing offerings in the wrong place', 'taking close-up photos of deity images during worship', 'turning your back to the shrine while posing for pictures', 'assuming every Hindu temple follows the same regional custom'],
    phrases: [
      { phrase: 'Namaste', meaning: 'a respectful greeting', whenToUse: 'you greet volunteers or hosts in a general Hindu setting' },
      { phrase: 'Prasad', meaning: 'food or another item that has been offered and then shared as blessed', whenToUse: 'you want to understand what is being distributed after worship' },
      { phrase: 'Darshan', meaning: 'sacred seeing, especially in relation to the deity', whenToUse: 'you are asking where the queue or line is moving' },
    ],
    phraseNotes: 'These words are widely known, but local languages and customs differ. Use them simply, and let the temple staff guide the details. Showing patience in the queue usually matters more than saying the perfect word.',
    relatedLinks: [
      { label: 'Hinduism profile', href: '/religions/hinduism' },
      { label: 'Hinduism reading list', href: '/recommended-reading/hinduism' },
    ],
  },
  {
    title: 'Visiting a Buddhist Temple Respectfully',
    tradition: 'Buddhism',
    setting: 'temples, viharas, and meditation halls',
    summaryFocus: 'modest dress, silence, bowing etiquette, shrine boundaries, and how to observe without interrupting practice',
    wearRequired: ['modest clothing that covers shoulders and knees', 'quiet shoes or sandals that are easy to remove', 'simple colors in stricter meditation settings', 'clothing that allows floor sitting if needed'],
    wearAvoid: ['shorts in formal temples', 'sleeveless tops', 'strong perfume', 'clothing that rustles loudly when you move or sit'],
    wearNotes: 'Buddhist communities differ across Theravada, Mahayana, Tibetan, and local cultural settings, but modest, quiet, non-showy clothing is almost always the safest choice. If a temple combines tourism and worship, remember that the ritual area is still a sacred environment. Dress for prayer, not for a sightseeing photo session.',
    bringHelpful: ['a silent phone', 'socks if the temple has a no-shoes policy', 'a small cash offering if the temple has a donation box', 'a water bottle only if you plan to keep it outside the shrine or meditation hall'],
    bringAvoid: ['food in the meditation area', 'flash cameras', 'large backpacks', 'objects placed casually on altars or near statues'],
    bringNotes: 'Many Buddhist temples have clear drop points for shoes, umbrellas, and bags. Use them. If you carry a bag into a hall, place it beside you, not on a chair or prayer cushion reserved for practitioners. Do not leave drinks near shrines, sutra tables, or chanting cushions.',
    arrivalWindow: '10 to 20 minutes before chanting, meditation, or a public teaching',
    arrivalTimingDetails: 'Arriving early lets you see whether the room expects bowing at the door, whether shoes come off at the entrance, and whether men and women sit in different sections. In meditation settings especially, late arrivals draw more attention than visitors expect because the room may be silent from the first minute.',
    arrivalFlow: 'You may pass through a courtyard or vestibule before entering a shrine hall. Watch whether people bow toward the Buddha image, remove shoes at the threshold, or wait for a bell before entering. In monasteries, a volunteer may show you where guests should sit, especially if monks or nuns are already seated in front.',
    whatHappens: ['quiet entry and seating', 'chanting, bells, or a short period of silent meditation', 'offerings of incense, flowers, or candles in some traditions', 'a Dharma talk or teaching', 'periods of bowing, standing, or seated stillness', 'informal greetings or tea after the program in some communities'],
    whatHappensNotes: 'Buddhist temples often communicate by rhythm rather than by constant verbal instruction. A bell may signal standing, seated meditation, or the end of chanting. Watch for how practitioners approach the shrine. They may bow with palms together, kneel, or sit cross-legged facing the altar. Visitors are not required to imitate all of this, but they must not interrupt it.',
    participationDo: ['enter quietly', 'follow seating guidance from staff or volunteers', 'bow lightly if that is the visible local norm and you are comfortable doing so', 'keep your body still during meditation periods'],
    participationAvoid: ['step over people or their meditation cushions', 'point your feet directly at the Buddha image if seated on the floor', 'speak during silent practice', 'touch ritual instruments, statues, or scriptures without invitation'],
    participationNotes: 'If you are seated on the floor and need to stretch your legs, do it discreetly and at the edge of the room if possible. If a monk or nun enters, many communities expect visitors to allow them to pass first. Showing bodily restraint is a major part of etiquette in Buddhist spaces, because stillness itself is often a form of practice.',
    commonMistakes: ['walking through a silent hall while talking', 'photographing monks or nuns up close without permission', 'treating the altar like a decorative backdrop', 'stepping over cushions, books, or prayer mats', 'turning meditation into a spectator experience', 'assuming one Buddhist custom applies to every temple'],
    phrases: [
      { phrase: 'Sadhu', meaning: 'well done, or a word of approval in some Buddhist communities', whenToUse: 'you hear the community use it first and understand the moment' },
      { phrase: 'Dharma', meaning: 'teaching or truth, depending on context', whenToUse: 'you are asking about a talk or class respectfully' },
      { phrase: 'Bhante', meaning: 'a respectful address for a monk in some Theravada settings', whenToUse: 'a local host tells you that this form of address is appropriate' },
    ],
    phraseNotes: 'Do not worry about specialized vocabulary on a first visit. Quiet movement, stillness, and careful observation matter more than terminology. If a community offers tea or conversation afterward, that is usually the right time to ask what forms of address they prefer.',
    relatedLinks: [
      { label: 'Buddhism profile', href: '/religions/buddhism' },
      { label: 'Buddhism reading list', href: '/recommended-reading/buddhism' },
    ],
  },
];
